In [18]:
import kagglehub
import os
import pandas as pd

# Download datasets
path_recommendation = kagglehub.dataset_download("arashnic/book-recommendation-dataset")
path_amazon = kagglehub.dataset_download("mohamedbakhet/amazon-books-reviews")
path_goodreads = kagglehub.dataset_download("jealousleopard/goodreadsbooks")

# Function to list files in each path
def list_files(path, name):
    print(f"\nFiles in {name}:")
    files = os.listdir(path)
    for file in files:
        print(f"- {file}")
    return files

# List files to confirm
list_files(path_recommendation, "Book Recommendation Dataset")
list_files(path_amazon, "Amazon Books Reviews")
list_files(path_goodreads, "Goodreads Books")

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).

Files in Book Recommendation Dataset:
- Books.csv
- classicRec.png
- DeepRec.png
- Ratings.csv
- recsys_taxonomy2.png
- Users.csv

Files in Amazon Books Reviews:
- books_data.csv
- Books_rating.csv

Files in Goodreads Books:
- books.csv

['books.csv']

BOOKS RECOMENDATIONS

BOOKS.CSV CLEAN

In [19]:
import pandas as pd
import os
import kagglehub

# Ensure the path is defined
path_recommendation = kagglehub.dataset_download("arashnic/book-recommendation-dataset")

# Define the file path and load
books_path = os.path.join(path_recommendation, 'Books.csv')
df_books = pd.read_csv(books_path, low_memory=False)

# Initial column normalization (lowercase, no spaces, no dots, no hyphens)
df_books.columns = df_books.columns.str.lower().str.replace(' ', '_').str.replace('-', '_').str.replace('.', '_')

# Diagnostic: Info, Nulls and Data Types
print("--- Info & Column Types ---")
df_books.info()

print("\n--- Count of Null Values ---")
print(df_books.isnull().sum())

print("\n--- Unique values in 'year_of_publication' (Sample) ---")
print(df_books['year_of_publication'].unique()[:15])

print(f"\nTotal Rows: {len(df_books)}")

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
--- Info & Column Types ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271360 entries, 0 to 271359
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   isbn                 271360 non-null  object
 1   book_title           271360 non-null  object
 2   book_author          271358 non-null  object
 3   year_of_publication  271360 non-null  object
 4   publisher            271358 non-null  object
 5   image_url_s          271360 non-null  object
 6   image_url_m          271360 non-null  object
 7   image_url_l          271357 non-null  object
dtypes: object(8)
memory usage: 16.6+ MB

--- Count of Null Values ---
isbn                   0
book_title             0
book_author            2
year_of_publication    0
publisher              2
image_url_s            0
image_url_m            0
image_url_l            3
dtype: int64

--- Unique values in 'year_of_publication' (Sample) ---
['2002' '2001' '1991' '1999' '2000' '1993' '1996' '1988' '2004' '1998'
 '1994' '2003' '1997' '1983' '1979']

Total Rows: 271360

In [20]:
# Filling Nulls
df_books['book_author'] = df_books['book_author'].fillna('unknown')
df_books['publisher'] = df_books['publisher'].fillna('unknown')
df_books['image_url_l'] = df_books['image_url_l'].fillna('no_url')

# Convert Year to Numeric (using errors='coerce' to turn strings into NaN)
df_books['year_of_publication'] = pd.to_numeric(df_books['year_of_publication'], errors='coerce')

# Text Normalization: Lowercase and strip spaces for all string columns
string_cols = ['book_title', 'book_author', 'publisher']
for col in string_cols:
    df_books[col] = df_books[col].astype(str).str.lower().str.strip()

# Check results
print("--- Final Check for Books.csv ---")
print(df_books.isnull().sum())
print(f"\nYear Dtype: {df_books['year_of_publication'].dtype}")

print(df_books[['book_title', 'book_author']].head())

--- Final Check for Books.csv ---
isbn                   0
book_title             0
book_author            0
year_of_publication    3
publisher              0
image_url_s            0
image_url_m            0
image_url_l            0
dtype: int64

Year Dtype: float64
                                          book_title           book_author
0                                classical mythology    mark p. o. morford
1                                       clara callan  richard bruce wright
2                               decision in normandy          carlo d'este
3  flu: the story of the great influenza pandemic...      gina bari kolata
4                             the mummies of urumchi       e. j. w. barber

In [21]:
# Drop unnecessary image columns
cols_to_drop = ['image_url_s', 'image_url_m', 'image_url_l']
df_books = df_books.drop(columns=cols_to_drop)

# Remove rows with any null values
# This will clean the remaining nulls in author, publisher and potential NaNs in year
df_books = df_books.dropna()

# Final verification of the clean dataframe
print("--- Final Columns ---")
print(df_books.columns.tolist())
print("\n--- Remaining Nulls ---")
print(df_books.isnull().sum())
print(f"\nTotal rows after cleaning: {len(df_books)}")
print("\n--- Preview ---")
print(df_books.head())

--- Final Columns ---
['isbn', 'book_title', 'book_author', 'year_of_publication', 'publisher']

--- Remaining Nulls ---
isbn                   0
book_title             0
book_author            0
year_of_publication    0
publisher              0
dtype: int64

Total rows after cleaning: 271357

--- Preview ---
         isbn                                         book_title  \
0  0195153448                                classical mythology
1  0002005018                                       clara callan
2  0060973129                               decision in normandy
3  0374157065  flu: the story of the great influenza pandemic...
4  0393045218                             the mummies of urumchi

            book_author  year_of_publication                   publisher
0    mark p. o. morford               2002.0     oxford university press
1  richard bruce wright               2001.0       harperflamingo canada
2          carlo d'este               1991.0             harperperennial
3      gina bari kolata               1999.0        farrar straus giroux
4       e. j. w. barber               1999.0  w. w. norton &amp; company

RATING CLEAN

In [22]:
# Load the Ratings file
import re

ratings_path = os.path.join(path_recommendation, 'Ratings.csv')
df_ratings = pd.read_csv(ratings_path, low_memory=False)

# Normalize column names
df_ratings.columns = df_ratings.columns.str.lower().str.replace(' ', '_').str.replace('-', '_').str.replace('.', '_')

# Initial Diagnostic
print("--- Ratings Info ---")
print(df_ratings.info())
print("\n--- Nulls in Ratings ---")
print(df_ratings.isnull().sum())

# Standardizing ISBN and Text
# It is crucial that ISBN matches the format in df_books
df_ratings['isbn'] = df_ratings['isbn'].astype(str).str.lower()
df_ratings['isbn'] = df_ratings['isbn'].apply(lambda x: re.sub(r'[^\w\s]', '', x))
df_ratings['isbn'] = df_ratings['isbn'].str.strip()

# 5.5 Check Rating distribution (optional but useful)
print("\n--- Rating Value Counts (Sample) ---")
print(df_ratings['book_rating'].value_counts().head())

--- Ratings Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1149780 entries, 0 to 1149779
Data columns (total 3 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   user_id      1149780 non-null  int64
 1   isbn         1149780 non-null  object
 2   book_rating  1149780 non-null  int64
dtypes: int64(2), object(1)
memory usage: 26.3+ MB
None

--- Nulls in Ratings ---
user_id        0
isbn           0
book_rating    0
dtype: int64

--- Rating Value Counts (Sample) ---
book_rating
0     716109
8     103736
10     78610
7      76457
9      67541
Name: count, dtype: int64

USERS CLEAN

In [23]:
# Load the raw file
users_path = os.path.join(path_recommendation, 'Users.csv')
df_users = pd.read_csv(users_path, low_memory=False)

# Standardize column names first (to work comfortably)
df_users.columns = df_users.columns.str.lower().str.replace(' ', '_').str.replace('-', '_').str.replace('.', '_')

# Diagnostic: Types and Nulls
print("--- Info & Types ---")
print(df_users.info())

print("\n--- Count of Nulls ---")
print(df_users.isnull().sum())

# Statistical summary of Age
print("\n--- Age Column Statistics ---")
print(df_users['age'].describe())

# Sample of Location strings
print("\n--- Sample of Location Data ---")
print(df_users['location'].head(15))

--- Info & Types ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278858 entries, 0 to 278857
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   user_id   278858 non-null  int64
 1   location  278858 non-null  object
 2   age       168096 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 6.4+ MB
None

--- Count of Nulls ---
user_id          0
location         0
age         110762
dtype: int64

--- Age Column Statistics ---
count    168096.000000
mean         34.751434
std          14.428097
min           0.000000
25%          24.000000
50%          32.000000
75%          44.000000
max         244.000000
Name: age, dtype: float64

--- Sample of Location Data ---
0                     nyc, new york, usa
1              stockton, california, usa
2        moscow, yukon territory, russia
3              porto, v.n.gaia, portugal
4     farnborough, hants, united kingdom
5          santa monica, california, usa
6                    washington, dc, usa
7               timmins, ontario, canada
8             germantown, tennessee, usa
9             albacete, wisconsin, spain
10        melbourne, victoria, australia
11           fort bragg, california, usa
12           barcelona, barcelona, spain
13                 mediapolis, iowa, usa
14              calgary, alberta, canada
Name: location, dtype: object

In [24]:
import numpy as np

# Cleaning Age: Replace outliers (under 5 and over 95) with NaN
df_users.loc[(df_users['age'] > 95) | (df_users['age'] < 5), 'age'] = np.nan

# Fill NaNs with the median (more robust than mean)
median_age = df_users['age'].median()
df_users['age'] = df_users['age'].fillna(median_age).astype(int)

# Split Location into City, State, Country
# We split by comma, and take only the first 3 parts if available
loc_split = df_users['location'].str.split(',', n=2, expand=True)
df_users['city'] = loc_split[0]
df_users['state'] = loc_split[1]
df_users['country'] = loc_split[2]

# Normalize and Clean the new columns
for col in ['city', 'state', 'country']:
    df_users[col] = df_users[col].astype(str).str.lower()
    # Remove special characters except spaces
    df_users[col] = df_users[col].apply(lambda x: re.sub(r'[^\w\s]', '', x))
    df_users[col] = df_users[col].str.strip()
    # Handle empty results from the split
    df_users.loc[df_users[col] == '', col] = 'unknown'

#  Drop original location column
df_users = df_users.drop(columns=['location'])

# Final check
print("--- Final Age Stats ---")
print(df_users['age'].describe())
print("\n--- Cleaned Users Sample ---")
print(df_users.head())

--- Final Age Stats ---
count    278858.000000
mean         33.638856
std          10.617503
min           5.000000
25%          29.000000
50%          32.000000
75%          35.000000
max          95.000000
Name: age, dtype: float64

--- Cleaned Users Sample ---
   user_id  age         city            state         country
0        1   32          nyc         new york             usa
1        2   18     stockton       california             usa
2        3   32       moscow  yukon territory          russia
3        4   17        porto           vngaia        portugal
4        5   32  farnborough            hants  united kingdom

In [25]:
#  Count unique values
unique_cities = df_users['city'].nunique()
unique_countries = df_users['country'].nunique()

print(f"Total unique cities: {unique_cities}")
print(f"Total unique countries: {unique_countries}")

# Top 20 Countries by user count
print("\n--- Top 20 Countries ---")
print(df_users['country'].value_counts().head(1120))

# Top 20 Cities by user count
print("\n--- Top 20 Cities ---")
print(df_users['city'].value_counts().head(30))

# Check for very short country names (potential errors)
print("\n--- Potential Country Errors (too short) ---")
print(df_users[df_users['country'].str.len() <= 2]['country'].unique())

Total unique cities: 32381
Total unique countries: 1120

--- Top 20 Countries ---
country
usa                        139190
canada                      21557
united kingdom              18311
germany                     17051
spain                       13198
                            ...
prchina china                   1
hebei china                     1
laoning china                   1
estado de mexico mexico         1
piemonte pakistan               1
Name: count, Length: 1120, dtype: int64

--- Top 20 Cities ---
city
london           4107
barcelona        2665
toronto          2342
madrid           1934
sydney           1885
portland         1869
melbourne        1863
vancouver        1699
chicago          1566
seattle          1541
new york         1445
milano           1390
san diego        1331
berlin           1306
ottawa           1303
san francisco    1300
houston          1241
paris            1191
roma             1045
austin           1044
los angeles      1042
calgary          1026
hamburg          1003
victoria          874
st louis          841
manchester        839
lisboa            803
singapore         801
christchurch      797
brisbane          792
Name: count, dtype: int64

--- Potential Country Errors (too short) ---
['lj' 'na' 'de' 'uk' 'ú' 'c' 'cn' 'ua' 'az' 'gb' 'pr' 'my' 'us' 'id' 'pa'
 'kz' 'u' 'z' 'l' 'nh' 'in' 'a' 'nz' 'x' 'nl']

In [26]:
# Dictionary for major country corrections
country_map = {
    'usa': 'usa',
    'united states': 'usa',
    'united kingdom': 'uk',
    'england': 'uk',
    'scotland': 'uk',
    'wales': 'uk',
    'china': 'china',
    'mexico': 'mexico',
    'spain': 'spain',
    'españa': 'spain',
    'canada': 'canada',
    'germany': 'germany',
    'deutschland': 'germany',
    'australia': 'australia',
    'italy': 'italy',
    'italia': 'italy',
    'france': 'france',
    'portugal': 'portugal',
    'brazil': 'brazil',
    'brasil': 'brazil',
    'india': 'india'
}

def clean_country_advanced(country):
    country = str(country).lower()
    # Check if any key from our map is inside the string
    for key, value in country_map.items():
        if key in country:
            return value
    return country # Return as is if no match found

# Apply the cleaning function
df_users['country'] = df_users['country'].apply(clean_country_advanced)

# Filter: Keep only countries with a minimum number of users to avoid "noise"
# For an expansion strategy, countries with 1 or 2 users are not statistically significant
country_counts = df_users['country'].value_counts()
major_countries = country_counts[country_counts >= 10].index
df_users.loc[~df_users['country'].isin(major_countries), 'country'] = 'other'

print("--- Top 125 Cleaned Countries ---")
print(df_users['country'].value_counts().head(125))

--- Top 125 Cleaned Countries ---
country
usa          139741
canada        21662
uk            18660
germany       17102
spain         13323
              ...
catalunya        13
benin            13
fiji             12
syria            12
ethiopia         12
Name: count, Length: 125, dtype: int64

In [27]:
# Count unique values after cleaning
final_unique_cities = df_users['city'].nunique()
final_unique_countries = df_users['country'].nunique()

print(f"Total unique cities after cleaning: {final_unique_cities}")
print(f"Total unique countries after cleaning: {final_unique_countries}")

# Calculate the coverage of our cleaning
other_count = (df_users['country'] == 'other').sum()
total_users = len(df_users)
coverage_pct = ((total_users - other_count) / total_users) * 100

print(f"\nUsers in major countries: {total_users - other_count} ({coverage_pct:.2f}%)")
print(f"Users classified as 'other': {other_count} ({100 - coverage_pct:.2f}%)")

Total unique cities after cleaning: 32381
Total unique countries after cleaning: 137

Users in major countries: 277843 (99.64%)
Users classified as 'other': 1015 (0.36%)

In [28]:
# Specific mapping for regions and duplicates
manual_map = {
    'catalunya': 'spain',
    'euskal herria': 'spain',
    'united arab emirates': 'uae',
    'urugua': 'uruguay',
    'na philippines': 'philippines',
    'na': 'unknown'
}

df_users['country'] = df_users['country'].replace(manual_map)

# Smart Imputation based on City/State
# We define a small dictionary of common cities to rescue 'unknown' countries
city_to_country = {
    'madrid': 'spain',
    'barcelona': 'spain',
    'london': 'uk',
    'nyc': 'usa',
    'new york': 'usa',
    'toronto': 'canada',
    'paris': 'france',
    'lisboa': 'portugal',
    'milan': 'italy'
}

def rescue_country(row):
    if row['country'] in ['unknown', 'other', 'na']:
        # Check city
        if row['city'] in city_to_country:
            return city_to_country[row['city']]
        # Check state
        if row['state'] in city_to_country:
            return city_to_country[row['state']]
    return row['country']

df_users['country'] = df_users.apply(rescue_country, axis=1)

# Final cleanup: replace anything still looking like 'na' with 'unknown'
df_users['country'] = df_users['country'].replace(['nan', 'other'], 'unknown')

In [29]:
# Count occurrences of 'unknown'
unknown_count = (df_users['country'] == 'unknown').sum()

# Count actual NaN values (nulls)
nan_count = df_users['country'].isna().sum()

# Count empty strings (if any)
empty_count = (df_users['country'] == '').sum()

print(f"Resultados de la búsqueda:")
print(f"- Total de 'unknown': {unknown_count}")
print(f"- Total de NaNs (nulos): {nan_count}")
print(f"- Total de cadenas vacías: {empty_count}")

# Mostrar porcentaje de datos limpios vs desconocidos
total_users = len(df_users)
clean_pct = ((total_users - unknown_count - nan_count) / total_users) * 100
print(f"\nCobertura final de países válidos: {clean_pct:.2f}%")

Resultados de la búsqueda:
- Total de 'unknown': 5375
- Total de NaNs (nulos): 0
- Total de cadenas vacías: 0

Cobertura final de países válidos: 98.07%

In [30]:
# Filtering users who are 'unknown' in all three geographic fields
total_unknown = df_users[
    (df_users['city'] == 'unknown') & 
    (df_users['state'] == 'unknown') & 
    (df_users['country'] == 'unknown')
]

# Calculating counts
num_total_unknown = len(total_unknown)
num_partial_unknown = 5375 - num_total_unknown # 5375 was your previous count

print(f"--- Análisis de Calidad Geográfica ---")
print(f"Usuarios sin NINGÚN dato (Ciudad, Estado y País son 'unknown'): {num_total_unknown}")
print(f"Usuarios con 'unknown' en país pero con Ciudad o Estado válido: {num_partial_unknown}")

# Previewing those who still have some data
if num_partial_unknown > 0:
    print("\n--- Muestra de usuarios con datos parciales (rescatables) ---")
    print(df_users[(df_users['country'] == 'unknown') & (df_users['city'] != 'unknown')][['city', 'state', 'country']].head(10))

--- Análisis de Calidad Geográfica ---
Usuarios sin NINGÚN dato (Ciudad, Estado y País son 'unknown'): 65
Usuarios con 'unknown' en país pero con Ciudad o Estado válido: 5310

--- Muestra de usuarios con datos parciales (rescatables) ---
                 city        state  country
18             weston      unknown  unknown
42             méxico  méxico city  unknown
90   torontonewmarket      unknown  unknown
256              quit         quit  unknown
257               ljk          lkj  unknown
311                lk          jlk  unknown
317            berlin           na  unknown
536             davis   california  unknown
557           burnaby      unknown  unknown
571             gabes        gabes  unknown

In [31]:
# Remove users with NO geographic data at all
df_users = df_users.drop(df_users[(df_users['city'] == 'unknown') & 
                                  (df_users['state'] == 'unknown') & 
                                  (df_users['country'] == 'unknown')].index)

# Smart Rescue: If city or state contains a known country name
valid_countries = [c for c in df_users['country'].unique() if c != 'unknown']

def final_geo_rescue(row):
    if row['country'] == 'unknown':
        # Check if the city or state mentions a known country
        for country in valid_countries:
            if country in str(row['city']) or country in str(row['state']):
                return country
    return row['country']

df_users['country'] = df_users.apply(final_geo_rescue, axis=1)

# Final Cut: Remove any remaining 'unknown' countries 
# (These are the ones with gibberish like 'ljk' or 'quit')
df_users = df_users[df_users['country'] != 'unknown']

print(f"--- Dataset Finalizado ---")
print(f"Total de usuarios finales: {len(df_users)}")
print(f"¿Nulos o unknowns en Country?: {df_users['country'].isin(['unknown']).sum()}")
print(f"Número de países únicos finales: {df_users['country'].nunique()}")

--- Dataset Finalizado ---
Total de usuarios finales: 273756
¿Nulos o unknowns en Country?: 0
Número de países únicos finales: 129

In [32]:
df_users.head()

   user_id  age         city            state   country
0        1   32          nyc         new york       usa
1        2   18     stockton       california       usa
2        3   32       moscow  yukon territory    russia
3        4   17        porto           vngaia  portugal
4        5   32  farnborough            hants        uk

UNION

In [33]:
# Check types for ISBN
print(f"ISBN type in Books: {df_books['isbn'].dtype}")
print(f"ISBN type in Ratings: {df_ratings['isbn'].dtype}")

# Check types for User_ID
print(f"User_ID type in Users: {df_users['user_id'].dtype}")
print(f"User_ID type in Ratings: {df_ratings['user_id'].dtype}")

# Quick check: How many ISBNs in Ratings actually exist in Books?
common_isbns = df_ratings['isbn'].isin(df_books['isbn']).sum()
print(f"\nRatings with a matching book: {common_isbns} out of {len(df_ratings)}")

ISBN type in Books: object
ISBN type in Ratings: object
User_ID type in Users: int64
User_ID type in Ratings: int64

Ratings with a matching book: 959960 out of 1149780

In [34]:
# First merge: Ratings + Books (Key: isbn)
df_temp = pd.merge(df_ratings, df_books, on='isbn', how='inner')

# Second merge: (Ratings+Books) + Users (Key: user_id)
df_master = pd.merge(df_temp, df_users, on='user_id', how='inner')

# Verify dimensions
print(f"Total rows in Master Dataset: {len(df_master)}")
print(f"Total columns: {len(df_master.columns)}")

# Export to CSV (Optional but recommended)
# df_master.to_csv('Master_Book_Data.csv', index=False)

print("\n--- Master Dataset Head ---")
print(df_master.head())

Total rows in Master Dataset: 927222
Total columns: 11

--- Master Dataset Head ---
   user_id        isbn  book_rating  \
0   276726  0155061224            5
1   276727  0446520802            0
2   276729  0521795028            6
3   276733  2080674722            0
4   276747  0060517794            9

                                          book_title         book_author  \
0                                   rites of passage          judith rae
1                                       the notebook     nicholas sparks
2  the amsterdam connection : level 4 (cambridge ...         sue leather
3                        les particules elementaires  michel houellebecq
4                           little altars everywhere       rebecca wells

   year_of_publication                   publisher  age       city  \
0               2001.0                      heinle   32    seattle
1               1996.0                warner books   16          h
2               2001.0  cambridge university press   16     rijeka
3               1998.0                  flammarion   37      paris
4               2003.0                 harpertorch   25  iowa city

             state    country
0       washington        usa
1  new south wales  australia
2               na    croatia
3               na     france
4             iowa        usa

DF GLOBAL BOOKS RECOMENDATION

In [35]:
df_master.info()
df_master.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 927222 entries, 0 to 927221
Data columns (total 11 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   user_id              927222 non-null  int64
 1   isbn                 927222 non-null  object
 2   book_rating          927222 non-null  int64
 3   book_title           927222 non-null  object
 4   book_author          927222 non-null  object
 5   year_of_publication  927222 non-null  float64
 6   publisher            927222 non-null  object
 7   age                  927222 non-null  int64
 8   city                 927222 non-null  object
 9   state                927222 non-null  object
 10  country              927222 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 77.8+ MB

,user_id,isbn,book_rating,book_title,book_author,year_of_publication,publisher,age,city,state,country
0,276726,0155061224,5,rites of passage,judith rae,2001.0,heinle,32,seattle,washington,usa
1,276727,0446520802,0,the notebook,nicholas sparks,1996.0,warner books,16,h,new south wales,australia
2,276729,0521795028,6,the amsterdam connection : level 4 (cambridge ...,sue leather,2001.0,cambridge university press,16,rijeka,na,croatia
3,276733,2080674722,0,les particules elementaires,michel houellebecq,1998.0,flammarion,37,paris,na,france
4,276747,0060517794,9,little altars everywhere,rebecca wells,2003.0,harpertorch,25,iowa city,iowa,usa

In [36]:
df_master = df_master.rename(columns={
    'book_rating': 'rating',
    'book_title': 'title',
    'book_author': 'author'
})

## Export Master DataFrame to CSV

import pandas as pd

# We use 'index=False' to prevent pandas from creating an extra column for the row numbers.
# We use 'encoding="utf-8"' to ensure special characters (like accents in book titles) are saved correctly.
df_master.to_csv('Master_RecomendationBook_Data.csv', index=False, encoding='utf-8')

print("Process Complete: 'Master_RecomendationBook_Data.csv' has been created.")

Process Complete: 'Master_RecomendationBook_Data.csv' has been created.

AMAZON

BOOKS CLEAN

In [37]:
import pandas as pd
import os

# Load the file
amazon_books_path = os.path.join(path_amazon, 'books_data.csv')
df_amazon_books = pd.read_csv(amazon_books_path)

# Basic Info: Data types and memory usage
print("--- 1. Data Types and Info ---")
print(df_amazon_books.info())

# Detailed Null Analysis (Count and Percentage)
null_counts = df_amazon_books.isnull().sum()
null_percentages = (null_counts / len(df_amazon_books)) * 100
null_report = pd.DataFrame({'Null Count': null_counts, 'Percentage (%)': null_percentages})

print("\n--- 2. Null Values Report ---")
print(null_report.sort_values(by='Percentage (%)', ascending=False))

# Statistical Summary of Numeric Columns
print("\n--- 3. Statistical Summary (Numeric) ---")
print(df_amazon_books.describe())

# Inspecting Object Columns (Categories, Price, Title)
print("\n--- 4. Sample of Categorical/Text Columns ---")
print(df_amazon_books.head(10))

--- 1. Data Types and Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212404 entries, 0 to 212403
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Title          212403 non-null  object
 1   description    143962 non-null  object
 2   authors        180991 non-null  object
 3   image          160329 non-null  object
 4   previewLink    188568 non-null  object
 5   publisher      136518 non-null  object
 6   publishedDate  187099 non-null  object
 7   infoLink       188568 non-null  object
 8   categories     171205 non-null  object
 9   ratingsCount   49752 non-null   float64
dtypes: float64(1), object(9)
memory usage: 16.2+ MB
None

--- 2. Null Values Report ---
               Null Count  Percentage (%)
ratingsCount       162652       76.576712
publisher           75886       35.727199
description         68442       32.222557
image               52075       24.516958
categories          41199       19.396527
authors             31413       14.789270
publishedDate       25305       11.913617
previewLink         23836       11.222011
infoLink            23836       11.222011
Title                   1        0.000471

--- 3. Statistical Summary (Numeric) ---
       ratingsCount
count  49752.000000
mean      21.252975
std      201.340431
min        1.000000
25%        1.000000
50%        2.000000
75%        5.000000
max     4895.000000

--- 4. Sample of Categorical/Text Columns ---
                                               Title  \
0                     Its Only Art If Its Well Hung!
1                           Dr. Seuss: American Icon
2              Wonderful Worship in Smaller Churches
3                      Whispers of the Wicked Saints
4  Nation Dance: Religion, Identity and Cultural ...
5  The Church of Christ: A Biblical Ecclesiology ...
6                         The Overbury affair (Avon)
7            A Walk in the Woods: a Play in Two Acts
8                           Saint Hyacinth of Poland
9  Rising Sons and Daughters: Life Among Japan's ...

                                         description  \
0                                                NaN
1  Philip Nel takes a fascinating look into the k...
2  This resource includes twelve principles in un...
3  Julia Thomas finds her life spinning out of co...
4                                                NaN
5  In The Church of Christ: A Biblical Ecclesiolo...
6                                                NaN
7                                                NaN
8  The story for children 10 and up of St. Hyacin...
9  Wardell recalls his experience as a foreign st...

                    authors  \
0          ['Julie Strain']
1            ['Philip Nel']
2          ['David R. Ray']
3       ['Veronica Haddon']
4           ['Edward Long']
5      ['Everett Ferguson']
6  ['Miriam Allen De Ford']
7          ['Lee Blessing']
8  ['Mary Fabyan Windeatt']
9        ['Steven Wardell']

                                               image  \
0  http://books.google.com/books/content?id=DykPA...
1  http://books.google.com/books/content?id=IjvHQ...
2  http://books.google.com/books/content?id=2tsDA...
3  http://books.google.com/books/content?id=aRSIg...
4                                                NaN
5  http://books.google.com/books/content?id=kVqRa...
6                                                NaN
7                                                NaN
8  http://books.google.com/books/content?id=lmLqA...
9                                                NaN

                                         previewLink  \
0  http://books.google.nl/books?id=DykPAAAACAAJ&d...
1  http://books.google.nl/books?id=IjvHQsCn_pgC&p...
2  http://books.google.nl/books?id=2tsDAAAACAAJ&d...
3  http://books.google.nl/books?id=aRSIgJlq6JwC&d...
4  http://books.google.nl/books?id=399SPgAACAAJ&d...
5  http://books.google.nl/books?id=kVqRaiPlx88C&p...
6  http://books.google.nl/books?id=mHLTngEACAAJ&d...
7  http://books.google.nl/books?id=6HDOwAEACAAJ&d...
8  http://books.google.nl/books?id=lmLqAAAACAAJ&d...
9  http://books.google.nl/books?id=rbLZugEACAAJ&d...

                    publisher publishedDate  \
0                         NaN          1996
1                   A&C Black    2005-01-01
2                         NaN          2000
3                   iUniverse       2005-02
4                         NaN    2003-03-01
5  Wm. B. Eerdmans Publishing          1996
6                         NaN          1960
7                         NaN          1988
8             Tan Books & Pub    2009-01-01
9          Plympton PressIntl          1995

                                            infoLink  \
0  http://books.google.nl/books?id=DykPAAAACAAJ&d...
1  http://books.google.nl/books?id=IjvHQsCn_pgC&d...
2  http://books.google.nl/books?id=2tsDAAAACAAJ&d...
3  http://books.google.nl/books?id=aRSIgJlq6JwC&d...
4  http://books.google.nl/books?id=399SPgAACAAJ&d...
5  http://books.google.nl/books?id=kVqRaiPlx88C&d...
6  http://books.google.nl/books?id=mHLTngEACAAJ&d...
7  http://books.google.nl/books?id=6HDOwAEACAAJ&d...
8  http://books.google.nl/books?id=lmLqAAAACAAJ&d...
9  http://books.google.nl/books?id=rbLZugEACAAJ&d...

                      categories  ratingsCount
0    ['Comics & Graphic Novels']           NaN
1  ['Biography & Autobiography']           NaN
2                   ['Religion']           NaN
3                    ['Fiction']           NaN
4                            NaN           NaN
5                   ['Religion']           5.0
6                            NaN           NaN
7                            NaN           3.0
8  ['Biography & Autobiography']           NaN
9             ['Social Science']           NaN

In [38]:
import re

# List of columns for aggressive cleaning (Excluding publishedDate)
text_cols = ['Title', 'description', 'authors', 'publisher', 'categories']

# Redefining deep clean for text only
def deep_clean_text(text):
    if pd.isna(text) or str(text).lower() == 'nan':
        return 'unknown'
    text = str(text).lower()
    # Removes everything except letters, numbers and spaces
    text = re.sub(r'[^a-z0-9\s]', '', text)
    return " ".join(text.split()).strip()

# Apply aggressive cleaning to text columns
for col in text_cols:
    if col in df_amazon_books.columns:
        df_amazon_books[col] = df_amazon_books[col].apply(deep_clean_text)

# Special handling for publishedDate (No regex, just basic cleanup)
df_amazon_books['publishedDate'] = df_amazon_books['publishedDate'].fillna('unknown').astype(str).str.strip()

# Verification
print("--- Amazon Data: Selective Cleaning Results ---")
print(df_amazon_books.head(10))

--- Amazon Data: Selective Cleaning Results ---
                                               Title  \
0                      its only art if its well hung
1                             dr seuss american icon
2              wonderful worship in smaller churches
3                      whispers of the wicked saints
4  nation dance religion identity and cultural di...
5  the church of christ a biblical ecclesiology f...
6                           the overbury affair avon
7             a walk in the woods a play in two acts
8                           saint hyacinth of poland
9  rising sons and daughters life among japans ne...

                                         description               authors  \
0                                            unknown          julie strain
1  philip nel takes a fascinating look into the k...            philip nel
2  this resource includes twelve principles in un...           david r ray
3  julia thomas finds her life spinning out of co...       veronica haddon
4                                            unknown           edward long
5  in the church of christ a biblical ecclesiolog...      everett ferguson
6                                            unknown  miriam allen de ford
7                                            unknown          lee blessing
8  the story for children 10 and up of st hyacint...  mary fabyan windeatt
9  wardell recalls his experience as a foreign st...        steven wardell

                                               image  \
0  http://books.google.com/books/content?id=DykPA...
1  http://books.google.com/books/content?id=IjvHQ...
2  http://books.google.com/books/content?id=2tsDA...
3  http://books.google.com/books/content?id=aRSIg...
4                                                NaN
5  http://books.google.com/books/content?id=kVqRa...
6                                                NaN
7                                                NaN
8  http://books.google.com/books/content?id=lmLqA...
9                                                NaN

                                         previewLink  \
0  http://books.google.nl/books?id=DykPAAAACAAJ&d...
1  http://books.google.nl/books?id=IjvHQsCn_pgC&p...
2  http://books.google.nl/books?id=2tsDAAAACAAJ&d...
3  http://books.google.nl/books?id=aRSIgJlq6JwC&d...
4  http://books.google.nl/books?id=399SPgAACAAJ&d...
5  http://books.google.nl/books?id=kVqRaiPlx88C&p...
6  http://books.google.nl/books?id=mHLTngEACAAJ&d...
7  http://books.google.nl/books?id=6HDOwAEACAAJ&d...
8  http://books.google.nl/books?id=lmLqAAAACAAJ&d...
9  http://books.google.nl/books?id=rbLZugEACAAJ&d...

                  publisher publishedDate  \
0                   unknown          1996
1                  ac black    2005-01-01
2                   unknown          2000
3                 iuniverse       2005-02
4                   unknown    2003-03-01
5  wm b eerdmans publishing          1996
6                   unknown          1960
7                   unknown          1988
8             tan books pub    2009-01-01
9        plympton pressintl          1995

                                            infoLink               categories  \
0  http://books.google.nl/books?id=DykPAAAACAAJ&d...    comics graphic novels
1  http://books.google.nl/books?id=IjvHQsCn_pgC&d...  biography autobiography
2  http://books.google.nl/books?id=2tsDAAAACAAJ&d...                 religion
3  http://books.google.nl/books?id=aRSIgJlq6JwC&d...                  fiction
4  http://books.google.nl/books?id=399SPgAACAAJ&d...                  unknown
5  http://books.google.nl/books?id=kVqRaiPlx88C&d...                 religion
6  http://books.google.nl/books?id=mHLTngEACAAJ&d...                  unknown
7  http://books.google.nl/books?id=6HDOwAEACAAJ&d...                  unknown
8  http://books.google.nl/books?id=lmLqAAAACAAJ&d...  biography autobiography
9  http://books.google.nl/books?id=rbLZugEACAAJ&d...           social science

   ratingsCount
0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
5           5.0
6           NaN
7           3.0
8           NaN
9           NaN

In [39]:
# Counting the 'unknown' label we created
unknown_summary = {}
for col in ['Title', 'description', 'authors', 'publisher', 'publishedDate', 'categories']:
    unknown_summary[col] = (df_amazon_books[col] == 'unknown').sum()

# Converting to DataFrame for a cleaner view
df_unknowns = pd.DataFrame.from_dict(unknown_summary, orient='index', columns=['Total Unknowns'])
df_unknowns['Percentage (%)'] = (df_unknowns['Total Unknowns'] / len(df_amazon_books)) * 100

print("--- Final Data Coverage Report ---")
print(df_unknowns.sort_values(by='Percentage (%)', ascending=False))

# Double check for any missed physical NaNs
print("\n--- Remaining Physical NaNs (Should be 0) ---")
print(df_amazon_books.isnull().sum())

--- Final Data Coverage Report ---
               Total Unknowns  Percentage (%)
publisher               75886       35.727199
description             68442       32.222557
categories              41199       19.396527
authors                 31413       14.789270
publishedDate           25305       11.913617
Title                       1        0.000471

--- Remaining Physical NaNs (Should be 0) ---
Title                 0
description           0
authors               0
image             52075
previewLink       23836
publisher             0
publishedDate         0
infoLink          23836
categories            0
ratingsCount     162652
dtype: int64

BOOKS Ratings CLEAN

In [40]:
# Load the reviews file
amazon_ratings_path = os.path.join(path_amazon, 'Books_rating.csv')
df_amazon_ratings = pd.read_csv(amazon_ratings_path)

# General Info: Row count and column types
print("--- 1. Data Types and Info ---")
print(df_amazon_ratings.info())

# Detailed Null Analysis
null_counts_rat = df_amazon_ratings.isnull().sum()
null_pct_rat = (null_counts_rat / len(df_amazon_ratings)) * 100
report_rat = pd.DataFrame({'Null Count': null_counts_rat, 'Percentage (%)': null_pct_rat})

print("\n--- 2. Null Values Report ---")
print(report_rat.sort_values(by='Percentage (%)', ascending=False))

# Statistical Summary (Scores and Prices)
print("\n--- 3. Statistical Summary ---")
print(df_amazon_ratings.describe())

# Preview of the main columns
print("\n--- 4. Data Sample (Title, Price, Score) ---")
# Adjusting column names based on typical Amazon dataset naming (Title, Price, review/score)
sample_cols = [col for col in ['Title', 'Price', 'review/score'] if col in df_amazon_ratings.columns]
print(df_amazon_ratings[sample_cols].head(10))

--- 1. Data Types and Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000000 entries, 0 to 2999999
Data columns (total 10 columns):
 #   Column              Dtype
---  ------              -----
 0   Id                  object
 1   Title               object
 2   Price               float64
 3   User_id             object
 4   profileName         object
 5   review/helpfulness  object
 6   review/score        float64
 7   review/time         int64
 8   review/summary      object
 9   review/text         object
dtypes: float64(2), int64(1), object(7)
memory usage: 228.9+ MB
None

--- 2. Null Values Report ---
                    Null Count  Percentage (%)
Price                  2518829       83.960967
profileName             561905       18.730167
User_id                 561787       18.726233
review/summary             407        0.013567
Title                      208        0.006933
review/text                  8        0.000267
Id                           0        0.000000
review/helpfulness           0        0.000000
review/time                  0        0.000000
review/score                 0        0.000000

--- 3. Statistical Summary ---
               Price  review/score   review/time
count  481171.000000  3.000000e+06  3.000000e+06
mean       21.762656  4.215289e+00  1.132307e+09
std        26.206541  1.203054e+00  1.493202e+08
min         1.000000  1.000000e+00 -1.000000e+00
25%        10.780000  4.000000e+00  9.999072e+08
50%        14.930000  5.000000e+00  1.128298e+09
75%        23.950000  5.000000e+00  1.269130e+09
max       995.000000  5.000000e+00  1.362355e+09

--- 4. Data Sample (Title, Price, Score) ---
                            Title  Price  review/score
0  Its Only Art If Its Well Hung!    NaN           4.0
1        Dr. Seuss: American Icon    NaN           5.0
2        Dr. Seuss: American Icon    NaN           5.0
3        Dr. Seuss: American Icon    NaN           4.0
4        Dr. Seuss: American Icon    NaN           4.0
5        Dr. Seuss: American Icon    NaN           4.0
6        Dr. Seuss: American Icon    NaN           5.0
7        Dr. Seuss: American Icon    NaN           5.0
8        Dr. Seuss: American Icon    NaN           5.0
9        Dr. Seuss: American Icon    NaN           4.0

In [41]:
import re

# Defining columns for text standardization
# Title is already cleaned; now we process the rest of the metadata
cols_to_standardize = ['Id', 'User_id', 'profileName', 'review/summary', 'review/text']

# Robust cleaning function (consistent with previous success)
def final_text_clean(text):
    if pd.isna(text) or str(text).lower() == 'nan':
        return 'unknown'
    text = str(text).lower()
    # Remove everything except letters, numbers, and spaces
    text = re.sub(r'[^a-z0-9\s]', '', text)
    # Collapse multiple spaces and trim edges
    return " ".join(text.split()).strip()

# Mass application to 3M rows
print("Standardizing columns... this is a heavy process, please wait.")
for col in cols_to_standardize:
    if col in df_amazon_ratings.columns:
        df_amazon_ratings[col] = df_amazon_ratings[col].apply(final_text_clean)
        print(f"Column '{col}' completed.")

# Quality check: Verification of clean strings and null removal
print("\n--- Final Standardization Verification ---")
print(df_amazon_ratings[cols_to_standardize + ['Title']].head(10))
print("\nPhysical Null Count (Should be 0 for these columns):")
print(df_amazon_ratings[cols_to_standardize].isnull().sum())

Standardizing columns... this is a heavy process, please wait.
Column 'Id' completed.
Column 'User_id' completed.
Column 'profileName' completed.
Column 'review/summary' completed.
Column 'review/text' completed.

--- Final Standardization Verification ---
           Id         User_id                      profileName  \
0  1882931173   avcgyzl8fqqtd                jim of oz jimofoz
1  0826414346  a30tk6u7dns82r                    kevin killian
2  0826414346  a3uh4uz4rsvo82                     john granger
3  0826414346  a2mvuwt453qh61  roy e perry amateur philosopher
4  0826414346  a22x4xupkf66mr      d h richards ninthwavestore
5  0826414346  a2f6nonfudb6uk                           malvin
6  0826414346  a14ojs0vwmoswo              midwest book review
7  0826414346  a2rssxtdzdush4                         j squire
8  0826414346  a25md5i2guiw6w            j p higbed big fellow
9  0826414346  a3va4xfs5wnjo3                  donald burnside

                                      review/summary  \
0             nice collection of julie strain images
1                                  really enjoyed it
2    essential for every personal and public library
3    phlip nel gives silly seuss a serious treatment
4                             good academic overview
5          one of americas greatest creative talents
6  a memorably excellent survey of dr seuss many ...
7                               academia at its best
8            and to think that i read it on the tram
9            fascinating account of a genius at work

                                         review/text  \
0  this is only for julie strain fans its a colle...
1  i dont care much for dr seuss but after readin...
2  if people become the books they read and if th...
3  theodore seuss geisel 19041991 aka quotdr seus...
4  philip nel dr seuss american iconthis is basic...
5  dr seuss american icon by philip nel is a thou...
6  theodor seuss giesel was best known as dr seus...
7  when i recieved this book as a gift for christ...
8  trams or any public transport are not usually ...
9  as far as i am aware this is the first booklen...

                            Title
0  Its Only Art If Its Well Hung!
1        Dr. Seuss: American Icon
2        Dr. Seuss: American Icon
3        Dr. Seuss: American Icon
4        Dr. Seuss: American Icon
5        Dr. Seuss: American Icon
6        Dr. Seuss: American Icon
7        Dr. Seuss: American Icon
8        Dr. Seuss: American Icon
9        Dr. Seuss: American Icon

Physical Null Count (Should be 0 for these columns):
Id                0
User_id           0
profileName       0
review/summary    0
review/text       0
dtype: int64

In [42]:
# Cleaning the Title column to match the metadata file
print("Normalizing Titles in the 3M dataset... please wait.")
df_amazon_ratings['Title'] = df_amazon_ratings['Title'].apply(final_text_clean)

# Final verification of the bridge column
print("\n--- Final Verification: Title Column ---")
print(df_amazon_ratings['Title'].head)

# Check for any remaining physical NaNs in Title
print(f"\nMissing Titles: {df_amazon_ratings['Title'].isnull().sum()}")

Normalizing Titles in the 3M dataset... please wait.

--- Final Verification: Title Column ---
<bound method NDFrame.head of 0          its only art if its well hung
1                 dr seuss american icon
2                 dr seuss american icon
3                 dr seuss american icon
4                 dr seuss american icon
                       ...
2999995              the idea of history
2999996              the idea of history
2999997              the idea of history
2999998              the idea of history
2999999              the idea of history
Name: Title, Length: 3000000, dtype: object>

Missing Titles: 0

In [43]:
# Fill NaN prices using the maximum price found for each Title
# This ensures consistency across multiple reviews of the same book
print("Propagating prices by title... this might take a minute for 3M rows.")
df_amazon_ratings['Price'] = df_amazon_ratings['Price'].fillna(
    df_amazon_ratings.groupby('Title')['Price'].transform('max')
)

# Verification of the progress
null_after = df_amazon_ratings['Price'].isnull().sum()
pct_after = (null_after / len(df_amazon_ratings)) * 100

print(f"\n--- Price Rescue Report ---")
print(f"Remaining Nulls in Price: {null_after}")
print(f"New Null Percentage: {pct_after:.2f}%")

Propagating prices by title... this might take a minute for 3M rows.

--- Price Rescue Report ---
Remaining Nulls in Price: 2433951
New Null Percentage: 81.13%

In [44]:
# Performing the merge on the 'Title' column
# This will align categories and authors with their respective prices and scores
print("Merging datasets... this might take a moment due to the 3M rows.")
df_amazon_master = pd.merge(df_amazon_ratings, df_amazon_books, on='Title', how='inner')

# Checking the result of the union
print("\n--- Amazon Master Dataset: Initial Audit ---")
print(f"Total rows after merge: {len(df_amazon_master)}")
print(f"Columns available: {df_amazon_master.columns.tolist()}")

# Check for nulls in critical columns after merge
print("\n--- Nulls in Master Dataset ---")
print(df_amazon_master[['Title', 'Price', 'categories', 'authors']].isnull().sum())

Merging datasets... this might take a moment due to the 3M rows.

--- Amazon Master Dataset: Initial Audit ---
Total rows after merge: 3616827
Columns available: ['Id', 'Title', 'Price', 'User_id', 'profileName', 'review/helpfulness', 'review/score', 'review/time', 'review/summary', 'review/text', 'description', 'authors', 'image', 'previewLink', 'publisher', 'publishedDate', 'infoLink', 'categories', 'ratingsCount']

--- Nulls in Master Dataset ---
Title               0
Price         2977607
categories          0
authors             0
dtype: int64

In [45]:
# Calculate the average price per category and fill NaNs
# We use transform('mean') to broadcast the category average to all missing rows
print("Imputing prices by category... this will finalize our economic data.")
df_amazon_master['Price'] = df_amazon_master['Price'].fillna(
    df_amazon_master.groupby('categories')['Price'].transform('mean')
)

# If any nulls remain (categories with no prices at all), we use the global mean
global_mean = df_amazon_master['Price'].mean()
df_amazon_master['Price'] = df_amazon_master['Price'].fillna(global_mean)

# Final audit of the Price column
final_nulls = df_amazon_master['Price'].isnull().sum()
print(f"\n--- Final Price Audit ---")
print(f"Remaining Nulls in Price: {final_nulls}")
print(f"Final Average Price in Dataset: {df_amazon_master['Price'].mean():.2f}")

# Quick look at the enriched data
print("\n--- Amazon Master Sample ---")
print(df_amazon_master[['Title', 'categories', 'Price', 'review/score']].head(10))

Imputing prices by category... this will finalize our economic data.

--- Final Price Audit ---
Remaining Nulls in Price: 0
Final Average Price in Dataset: 21.93

--- Amazon Master Sample ---
                           Title               categories      Price  \
0  its only art if its well hung    comics graphic novels  13.184161
1         dr seuss american icon  biography autobiography  18.583430
2         dr seuss american icon  biography autobiography  18.583430
3         dr seuss american icon  biography autobiography  18.583430
4         dr seuss american icon  biography autobiography  18.583430
5         dr seuss american icon  biography autobiography  18.583430
6         dr seuss american icon  biography autobiography  18.583430
7         dr seuss american icon  biography autobiography  18.583430
8         dr seuss american icon  biography autobiography  18.583430
9         dr seuss american icon  biography autobiography  18.583430

   review/score
0           4.0
1           5.0
2           5.0
3           4.0
4           4.0
5           4.0
6           5.0
7           5.0
8           5.0
9           4.0

In [46]:
df_amazon_master.info()
df_amazon_master.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3616827 entries, 0 to 3616826
Data columns (total 19 columns):
 #   Column              Dtype
---  ------              -----
 0   Id                  object
 1   Title               object
 2   Price               float64
 3   User_id             object
 4   profileName         object
 5   review/helpfulness  object
 6   review/score        float64
 7   review/time         int64
 8   review/summary      object
 9   review/text         object
 10  description         object
 11  authors             object
 12  image               object
 13  previewLink         object
 14  publisher           object
 15  publishedDate       object
 16  infoLink            object
 17  categories          object
 18  ratingsCount        float64
dtypes: float64(3), int64(1), object(15)
memory usage: 524.3+ MB

,Id,Title,Price,User_id,profileName,review/helpfulness,review/score,review/time,review/summary,review/text,description,authors,image,previewLink,publisher,publishedDate,infoLink,categories,ratingsCount
0,1882931173,its only art if its well hung,13.184161,avcgyzl8fqqtd,jim of oz jimofoz,7/7,4.0,940636800,nice collection of julie strain images,this is only for julie strain fans its a colle...,unknown,julie strain,http://books.google.com/books/content?id=DykPA...,http://books.google.nl/books?id=DykPAAAACAAJ&d...,unknown,1996,http://books.google.nl/books?id=DykPAAAACAAJ&d...,comics graphic novels,NaN
1,0826414346,dr seuss american icon,18.583430,a30tk6u7dns82r,kevin killian,10/10,5.0,1095724800,really enjoyed it,i dont care much for dr seuss but after readin...,philip nel takes a fascinating look into the k...,philip nel,http://books.google.com/books/content?id=IjvHQ...,http://books.google.nl/books?id=IjvHQsCn_pgC&p...,ac black,2005-01-01,http://books.google.nl/books?id=IjvHQsCn_pgC&d...,biography autobiography,NaN
2,0826414346,dr seuss american icon,18.583430,a3uh4uz4rsvo82,john granger,10/11,5.0,1078790400,essential for every personal and public library,if people become the books they read and if th...,philip nel takes a fascinating look into the k...,philip nel,http://books.google.com/books/content?id=IjvHQ...,http://books.google.nl/books?id=IjvHQsCn_pgC&p...,ac black,2005-01-01,http://books.google.nl/books?id=IjvHQsCn_pgC&d...,biography autobiography,NaN
3,0826414346,dr seuss american icon,18.583430,a2mvuwt453qh61,roy e perry amateur philosopher,7/7,4.0,1090713600,phlip nel gives silly seuss a serious treatment,theodore seuss geisel 19041991 aka quotdr seus...,philip nel takes a fascinating look into the k...,philip nel,http://books.google.com/books/content?id=IjvHQ...,http://books.google.nl/books?id=IjvHQsCn_pgC&p...,ac black,2005-01-01,http://books.google.nl/books?id=IjvHQsCn_pgC&d...,biography autobiography,NaN
4,0826414346,dr seuss american icon,18.583430,a22x4xupkf66mr,d h richards ninthwavestore,3/3,4.0,1107993600,good academic overview,philip nel dr seuss american iconthis is basic...,philip nel takes a fascinating look into the k...,philip nel,http://books.google.com/books/content?id=IjvHQ...,http://books.google.nl/books?id=IjvHQsCn_pgC&p...,ac black,2005-01-01,http://books.google.nl/books?id=IjvHQsCn_pgC&d...,biography autobiography,NaN

DF MASTER AMAZON BOOKS

In [47]:
import pandas as pd

# 1. List of selected columns
selected_columns = [
    'Id', 'Title', 'Price', 'User_id', 'review/score', 
    'authors', 'publisher', 'publishedDate', 'categories', 'ratingsCount'
]

# 2. Apply filter to the main DataFrame
df_amazon_master = df_amazon_master[selected_columns]

# 3. Rename columns for a more professional look (snake_case)
# This step is optional but highly recommended for data analysts
df_amazon_master.columns = [
    'book_id', 'title', 'price', 'user_id', 'rating', 
    'authors', 'publisher', 'published_date', 'categories', 'ratings_count'
]

df_amazon_master = df_amazon_master.rename(columns={
    'authors': 'author',
    'published_date': 'publication_date',
})
# 4. Final Verification
print("--- Final Dataset Information ---")
print(df_amazon_master.info())

--- Final Dataset Information ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3616827 entries, 0 to 3616826
Data columns (total 10 columns):
 #   Column            Dtype
---  ------            -----
 0   book_id           object
 1   title             object
 2   price             float64
 3   user_id           object
 4   rating            float64
 5   author            object
 6   publisher         object
 7   publication_date  object
 8   categories        object
 9   ratings_count     float64
dtypes: float64(3), object(7)
memory usage: 275.9+ MB
None

In [48]:
# Conteo total de celdas en la columna (incluyendo repetidos y nulos)
total_filas = len(df_amazon_master['categories'])

# Conteo de valores no nulos
datos_reales = df_amazon_master['categories'].count()

# Conteo de categorías únicas (lo que tú mencionabas)
categorias_unicas = df_amazon_master['categories'].nunique()

print(f"Total de filas en el DataFrame: {total_filas}")
print(f"Celdas con información de categoría: {datos_reales}")
print(f"Nombres de categorías distintos: {categorias_unicas}")

Total de filas en el DataFrame: 3616827
Celdas con información de categoría: 3616827
Nombres de categorías distintos: 10602

In [49]:
# TITLE: Overcoming Merge Issues with Dictionary Mapping and Character Stripping

import pandas as pd
import re

# 1. LOAD DATA SOURCES
df_manual = pd.read_csv('unique_titles_book_id.csv', dtype=str)
df_llm = pd.read_csv('classification_results.csv', dtype=str)

# 2. DEFINITIVE CLEANING FUNCTION
# This function removes ANY non-alphanumeric character (spaces, dots, etc.)
def extreme_clean(val):
    if pd.isna(val): return ""
    # Convert to string, remove '.0', and keep only letters and numbers
    s = str(val).split('.')[0].upper()
    return re.sub(r'[^A-Z0-9]', '', s)

# Apply to all sources
df_manual['id_clean'] = df_manual['book_id'].apply(extreme_clean)
df_llm['id_clean'] = df_llm['book_id'].apply(extreme_clean)
df_amazon_master['id_clean'] = df_amazon_master['book_id'].apply(extreme_clean)

# 3. CREATE CONSOLIDATED CATEGORY DICTIONARY
# Priority: Manual > LLM
manual_dict = df_manual.dropna(subset=['categories']).set_index('id_clean')['categories'].to_dict()
llm_dict = df_llm.dropna(subset=['parent_category']).set_index('id_clean')['parent_category'].to_dict()

# Merge dictionaries (Manual overwrites LLM)
final_category_map = {**llm_dict, **manual_dict}

# 4. DIAGNOSTIC: Check if the specific ID exists in the map
test_id = extreme_clean('1882931173')
print(f"Is ID {test_id} in the map? {'Yes' if test_id in final_category_map else 'No'}")
if test_id in final_category_map:
    print(f"Category found for {test_id}: {final_category_map[test_id]}")

# 5. ASSIGN CATEGORIES USING .map()
# This is more efficient and less error-prone than a join for this case
if 'parent_category' in df_amazon_master.columns:
    df_amazon_master = df_amazon_master.drop(columns=['parent_category'])

df_amazon_master['parent_category'] = df_amazon_master['id_clean'].map(final_category_map)

# 6. VERIFICATION
matched = df_amazon_master['parent_category'].notnull().sum()
print(f"\nFinal categorization count: {matched}")

# Cleanup: remove temporary join column
df_amazon_master = df_amazon_master.drop(columns=['id_clean'])

Is ID 1882931173 in the map? Yes
Category found for 1882931173: comics graphic novels

Final categorization count: 3616827

In [50]:
# 1. LOAD DATA
# Loading both files as strings to prevent ID corruption
df_man = pd.read_csv('unique_titles_book_id.csv', dtype=str)
df_llm = pd.read_csv('classification_results.csv', dtype=str)

# 2. STANDARDIZE JOIN KEYS
# Using the alphanumeric cleaning to ensure IDs match regardless of format
def clean_id(val):
    if pd.isna(val): return ""
    return "".join(filter(str.isalnum, str(val).upper()))

df_man['id_clean'] = df_man['book_id'].apply(clean_id)
df_llm['id_clean'] = df_llm['book_id'].apply(clean_id)

# 3. CREATE THE UNIFIED MAP
# We extract the 'parent_category' from both. 
# We drop rows where the category is missing to avoid overwriting with NaNs.
man_map = df_man.dropna(subset=['parent_category']).set_index('id_clean')['parent_category'].to_dict()
llm_map = df_llm.dropna(subset=['parent_category']).set_index('id_clean')['parent_category'].to_dict()

# 4. CONSOLIDATE (Manual Overwrites LLM)
# By putting llm_map first and man_map second, the manual labels win
unified_map = {**llm_map, **man_map}

# 5. APPLY TO MASTER DATASET
# Pre-cleaning the master IDs for the mapping process
df_amazon_master['id_clean'] = df_amazon_master['book_id'].apply(clean_id)

# Drop old category columns if they exist to start fresh
if 'parent_category' in df_amazon_master.columns:
    df_amazon_master = df_amazon_master.drop(columns=['parent_category'])

df_amazon_master['parent_category'] = df_amazon_master['id_clean'].map(unified_map)

# 6. RESULTS SUMMARY
total_rows = len(df_amazon_master)
categorized = df_amazon_master['parent_category'].notnull().sum()
print(f"Total rows in Master: {total_rows}")
print(f"Successfully unified and categorized: {categorized}")

Total rows in Master: 3616827
Successfully unified and categorized: 3616382

In [51]:
# TITLE: Frequency Analysis of Final Categories

# 1. LIST ALL UNIQUE CATEGORIES
# This shows every distinct label present in your unified column
unique_categories = df_amazon_master['parent_category'].unique()
print(f"Total unique categories found: {len(unique_categories)}")
print("-" * 30)
print(unique_categories)

# 2. COUNT FREQUENCY OF EACH CATEGORY
# This is better for Power BI prep, as it shows if some categories 
# have very few books (which might indicate a typo or error)
category_counts = df_amazon_master['parent_category'].value_counts()

print("\nTop 20 categories by book count:")
print(category_counts.head(20))

# 3. IDENTIFY MISSING VALUES
# To see how many books couldn't be matched at all
missing = df_amazon_master['parent_category'].isna().sum()
print(f"\nBooks without category (NaN): {missing}")

Total unique categories found: 33
------------------------------
['Novels' 'Biography' 'Religion' 'Fiction' 'History' 'Theater'
 'Social sciences' 'Education' 'Young' 'Science & Tech' 'Law'
 'Political science' 'Lifestyle' 'travel' 'Psych' 'No fiction'
 'Architecture' 'Art' 'Literature' 'Business' 'Pets' 'Science fiction'
 'Travel' 'Languages' 'Music' 'Other' 'Photography' 'history' 'pets'
 'education' 'religion' 'young' nan]

Top 20 categories by book count:
parent_category
Fiction              1425024
Novels                309525
Lifestyle             213023
Religion              193026
History               164045
Biography             162883
Young                 155501
Science & Tech        137594
Education             116480
Psych                 101674
Business              100137
Social sciences        99647
Science fiction        77029
Theater                54085
Travel                 50449
Art                    36039
Political science      34755
Literature             31659
No fiction             25047
Other                  22172
Name: count, dtype: int64

Books without category (NaN): 445

In [52]:
# Filtrar solo los que siguen siendo 'Other'
df_others = df_amazon_master[df_amazon_master['parent_category'] == 'Other']

# Ver las 20 categorías originales de Amazon más comunes dentro de este grupo
print("Categorías originales en el grupo 'Other':")
print(df_others['categories'].value_counts().head(20))

Categorías originales en el grupo 'Other':
categories
unknown                               8469
audiobooks                            6725
manhattan new york ny                 1757
museum visitors                        416
dungeons and dragons game              104
blair witch project motion picture     103
atlanta ga                              98
american wit and humor pictorial        94
netherlands                             88
contract bridge                         85
ghosts                                  78
library catalogs                        78
taiwan                                  78
computer printers                       70
actresses                               69
schools                                 68
spanishamerican war 1898                63
automobile drivers                      61
marriage                                57
firearms                                56
Name: count, dtype: int64

In [53]:
#  Targeted Rescue of 'Other' Categories
# Diccionario de rescate basado en tus categorías de Amazon encontradas
rescue_map = {
    'audiobooks': 'Entertainment',
    'manhattan new york ny': 'Travel',
    'atlanta ga': 'Travel',
    'netherlands': 'Travel',
    'taiwan': 'Travel',
    'museum visitors': 'Travel',
    'automobile drivers': 'Lifestyle',
    'dungeons and dragons game': 'Entertainment',
    'blair witch project motion picture': 'Entertainment',
    'contract bridge': 'Lifestyle',
    'ghosts': 'Religion',  
    'library catalogs': 'Education',
    'computer printers': 'Science & Tech',
    'actresses': 'Biography',
    'schools': 'Education',
    'spanishamerican war 1898': 'History',
    'marriage': 'Social sciences',
    'firearms': 'Lifestyle',
    'arka tech': 'Science & Tech'
}

def final_refinement(row):
    if row['parent_category'] == 'Other':
        cat_original = str(row['categories']).lower()
        
        # 1. Intentar coincidencia exacta o contenida del mapa de rescate
        for key, target_cat in rescue_map.items():
            if key in cat_original:
                return target_cat
        
        # 2. Si sigue siendo 'unknown', podemos dejarlo como 'Other' 
        # o moverlo a una categoría más limpia como 'General / Unknown'
        if 'unknown' in cat_original:
            return 'General Interest'
            
    return row['parent_category']

# Aplicar el refinamiento
df_amazon_master['parent_category'] = df_amazon_master.apply(final_refinement, axis=1)

# Ver el nuevo estado de 'Other'
print(f"Registros restantes en 'Other': {df_amazon_master['parent_category'].value_counts().get('Other', 0)}")
print("\nDistribución de las categorías rescatadas:")
print(df_amazon_master['parent_category'].value_counts().head(10))

Registros restantes en 'Other': 3578

Distribución de las categorías rescatadas:
parent_category
Fiction           1425024
Novels             309525
Lifestyle          213228
Religion           193104
History            164108
Biography          162965
Young              155501
Science & Tech     137719
Education          116626
Psych              101674
Name: count, dtype: int64

In [54]:
df_amazon_master.head()

,book_id,title,price,user_id,rating,author,publisher,publication_date,categories,ratings_count,id_clean,parent_category
0,1882931173,its only art if its well hung,13.184161,avcgyzl8fqqtd,4.0,julie strain,unknown,1996,comics graphic novels,NaN,1882931173,Novels
1,0826414346,dr seuss american icon,18.583430,a30tk6u7dns82r,5.0,philip nel,ac black,2005-01-01,biography autobiography,NaN,0826414346,Biography
2,0826414346,dr seuss american icon,18.583430,a3uh4uz4rsvo82,5.0,philip nel,ac black,2005-01-01,biography autobiography,NaN,0826414346,Biography
3,0826414346,dr seuss american icon,18.583430,a2mvuwt453qh61,4.0,philip nel,ac black,2005-01-01,biography autobiography,NaN,0826414346,Biography
4,0826414346,dr seuss american icon,18.583430,a22x4xupkf66mr,4.0,philip nel,ac black,2005-01-01,biography autobiography,NaN,0826414346,Biography

In [55]:
# 1. DEFINE THE COLUMNS TO KEEP
# We select the specific fields you requested for the final dataset
final_columns = [
    'book_id', 
    'title', 
    'price', 
    'user_id', 
    'rating', 
    'author', 
    'publisher', 
    'publication_date', 
    'ratings_count', 
    'parent_category'
]

# 2. FILTER THE DATAFRAME
# This creates a clean copy with only the relevant columns
df_amazon_final = df_amazon_master[final_columns].copy()

# 3. RENAME THE CATEGORY COLUMN
# Changing 'parent_category' to 'categories' as the final name
df_amazon_final = df_amazon_final.rename(columns={'parent_category': 'categories'})

# 4. EXPORT TO CSV
# Saving the final result without the index to keep the file size optimized
output_file = 'Master_AmazonBooks_Data.csv.csv'
df_amazon_final.to_csv(output_file, index=False)

print(f"Dataset successfully exported to: {output_file}")
print("Final Columns:", df_amazon_final.columns.tolist())

Dataset successfully exported to: Master_AmazonBooks_Data.csv.csv
Final Columns: ['book_id', 'title', 'price', 'user_id', 'rating', 'author', 'publisher', 'publication_date', 'ratings_count', 'categories']

GOODREADS BOOKS CLEAN

In [56]:
import pandas as pd
import os
import re

# Load Goodreads books with the correct syntax
goodreads_books_path = os.path.join(path_goodreads, 'books.csv')
df_goodreads = pd.read_csv(goodreads_books_path, on_bad_lines='skip')

# Initial Null Audit
print("--- Initial Null Analysis (Goodreads) ---")
print(df_goodreads.isnull().sum())

# Handling Nulls before standardization
# For text columns, we use 'unknown'. For numeric ratings, we'll keep them as is for now.
df_goodreads['title'] = df_goodreads['title'].fillna('unknown')
df_goodreads['authors'] = df_goodreads['authors'].fillna('unknown')
df_goodreads['publisher'] = df_goodreads['publisher'].fillna('unknown')

# Aggressive Standardization Function
def gr_deep_clean(text):
    if pd.isna(text) or str(text).lower() == 'nan':
        return 'unknown'
    text = str(text).lower()
    # Keep only letters, numbers and spaces
    text = re.sub(r'[^a-z0-9\s]', '', text)
    # Remove extra spaces
    return " ".join(text.split()).strip()

# Applying standardization to key columns
cols_to_fix = ['title', 'authors', 'publisher']
for col in cols_to_fix:
    df_goodreads[col] = df_goodreads[col].apply(gr_deep_clean)

# Global renaming for future matching
df_goodreads = df_goodreads.rename(columns={'title': 'Title'})

# Final Verification of Goodreads Data Quality
print("\n--- Final Quality Report: Goodreads ---")
print(df_goodreads[['Title', 'authors', 'average_rating']].head(10))
print("\nRemaining physical nulls in text columns:")
print(df_goodreads[['Title', 'authors', 'publisher']].isnull().sum())

--- Initial Null Analysis (Goodreads) ---
bookID                0
title                 0
authors               0
average_rating        0
isbn                  0
isbn13                0
language_code         0
  num_pages           0
ratings_count         0
text_reviews_count    0
publication_date      0
publisher             0
dtype: int64

--- Final Quality Report: Goodreads ---
                                               Title                 authors  \
0  harry potter and the halfblood prince harry po...  jk rowlingmary grandpr
1  harry potter and the order of the phoenix harr...  jk rowlingmary grandpr
2  harry potter and the chamber of secrets harry ...              jk rowling
3  harry potter and the prisoner of azkaban harry...  jk rowlingmary grandpr
4    harry potter boxed set books 15 harry potter 15  jk rowlingmary grandpr
5  unauthorized harry potter book seven news half...   w frederick zimmerman
6            harry potter collection harry potter 16              jk rowling
7  the ultimate hitchhikers guide five complete n...           douglas adams
8  the ultimate hitchhikers guide to the galaxy h...           douglas adams
9  the hitchhikers guide to the galaxy hitchhiker...           douglas adams

   average_rating
0            4.57
1            4.49
2            4.42
3            4.56
4            4.78
5            3.74
6            4.73
7            4.38
8            4.38
9            4.22

Remaining physical nulls in text columns:
Title        0
authors      0
publisher    0
dtype: int64

DF GOODREADS

In [57]:
## Exporting Cleaned Goodreads Data
import pandas as pd

# 1. Define the output filename
output_file = 'Master_GoodreadsBooks_Data.csv'

# Also ensuring 'Title' becomes 'title' and 'bookID' becomes 'book_id' for consistency
df_goodreads = df_goodreads.rename(columns={
    'bookID': 'book_id',
    'Title': 'title',
    'authors': 'author',
    'ratings_count': 'rating'
})
# 2. Export the DataFrame
# We use index=False to keep the CSV clean
# We use encoding='utf-8' to preserve any special characters after the regex clean
df_goodreads.to_csv(output_file, index=False, encoding='utf-8')

print(f"Success: {output_file} has been saved with cleaned and standardized data.")

Success: Master_GoodreadsBooks_Data.csv has been saved with cleaned and standardized data.

In [58]:
df_amazon_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3616827 entries, 0 to 3616826
Data columns (total 12 columns):
 #   Column            Dtype
---  ------            -----
 0   book_id           object
 1   title             object
 2   price             float64
 3   user_id           object
 4   rating            float64
 5   author            object
 6   publisher         object
 7   publication_date  object
 8   categories        object
 9   ratings_count     float64
 10  id_clean          object
 11  parent_category   object
dtypes: float64(3), object(9)
memory usage: 331.1+ MB

In [59]:
df_amazon_master.head()

,book_id,title,price,user_id,rating,author,publisher,publication_date,categories,ratings_count,id_clean,parent_category
0,1882931173,its only art if its well hung,13.184161,avcgyzl8fqqtd,4.0,julie strain,unknown,1996,comics graphic novels,NaN,1882931173,Novels
1,0826414346,dr seuss american icon,18.583430,a30tk6u7dns82r,5.0,philip nel,ac black,2005-01-01,biography autobiography,NaN,0826414346,Biography
2,0826414346,dr seuss american icon,18.583430,a3uh4uz4rsvo82,5.0,philip nel,ac black,2005-01-01,biography autobiography,NaN,0826414346,Biography
3,0826414346,dr seuss american icon,18.583430,a2mvuwt453qh61,4.0,philip nel,ac black,2005-01-01,biography autobiography,NaN,0826414346,Biography
4,0826414346,dr seuss american icon,18.583430,a22x4xupkf66mr,4.0,philip nel,ac black,2005-01-01,biography autobiography,NaN,0826414346,Biography

In [60]:
df_goodreads.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11123 entries, 0 to 11122
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   book_id             11123 non-null  int64
 1   title               11123 non-null  object
 2   author              11123 non-null  object
 3   average_rating      11123 non-null  float64
 4   isbn                11123 non-null  object
 5   isbn13              11123 non-null  int64
 6   language_code       11123 non-null  object
 7     num_pages         11123 non-null  int64
 8   rating              11123 non-null  int64
 9   text_reviews_count  11123 non-null  int64
 10  publication_date    11123 non-null  object
 11  publisher           11123 non-null  object
dtypes: float64(1), int64(5), object(6)
memory usage: 1.0+ MB

In [61]:
df_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 927222 entries, 0 to 927221
Data columns (total 11 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   user_id              927222 non-null  int64
 1   isbn                 927222 non-null  object
 2   rating               927222 non-null  int64
 3   title                927222 non-null  object
 4   author               927222 non-null  object
 5   year_of_publication  927222 non-null  float64
 6   publisher            927222 non-null  object
 7   age                  927222 non-null  int64
 8   city                 927222 non-null  object
 9   state                927222 non-null  object
 10  country              927222 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 77.8+ MB

In [62]:
# Probando la tasa de éxito de unión entre ISBN/Book_ID y Título

# 1. Normalización rápida para la prueba
# Recomendaciones
df_master['isbn_clean'] = df_master['isbn'].astype(str).str.strip().str.upper()
df_master['title_clean'] = df_master['title'].astype(str).str.strip().str.lower()

# Amazon
df_amazon_final['book_id_clean'] = df_amazon_final['book_id'].astype(str).str.strip().str.upper()
df_amazon_final['title_clean'] = df_amazon_final['title'].astype(str).str.strip().str.lower()

# 2. Prueba A: ¿Es el book_id el ISBN?
match_id = pd.merge(df_master, df_amazon_final, left_on='isbn_clean', right_on='book_id_clean')
print(f"📊 Coincidencias por ID (ISBN vs Book_ID): {len(match_id)}")

# 3. Prueba B: ¿Funciona mejor el Título?
match_title = pd.merge(df_master, df_amazon_final, on='title_clean')
print(f"📊 Coincidencias por Título: {len(match_title)}")

# 4. Ver un ejemplo de los fallos si match_id es bajo
if len(match_id) < 100:
    print("\nEjemplo de IDs que no cruzan:")
    print("ISBN en Reco:", df_master['isbn_clean'].iloc[0])
    print("Book_ID en Amazon:", df_amazon_final['book_id_clean'].iloc[0])

📊 Coincidencias por ID (ISBN vs Book_ID): 3632133
📊 Coincidencias por Título: 86886133

CREATE: SQL TABLES

In [63]:
from sqlalchemy import create_engine, text

# 1. Conexión con tus credenciales confirmadas
engine = create_engine('mysql+pymysql://root:18121996@localhost/bookproject_db')

def clean_and_upload(df, table_name):
    try:
        with engine.connect() as connection:
            # Borramos la tabla manualmente para evitar errores de metadatos
            print(f"🗑️  Limpiando tabla {table_name} si existe...")
            connection.execute(text(f"DROP TABLE IF EXISTS {table_name}"))
            connection.commit()
        
        # Subida de datos
        print(f"📤 Subiendo datos a {table_name}...")
        # Usamos chunksize para no saturar la memoria RAM
        df.to_sql(table_name, con=engine, if_exists='append', index=False, chunksize=5000)
        print(f"✅ {table_name} subida con éxito.")
    except Exception as e:
        print(f"❌ Error en {table_name}: {e}")

# 2. Ejecución con tus nombres de variables correctos
clean_and_upload(df_goodreads, 'Table_Goodreads')
clean_and_upload(df_master, 'Table_Recommendations')
clean_and_upload(df_amazon_final, 'Table_Amazon')

print("\n✨ ¡PROCESO FINALIZADO! Ya puedes consultar tus tablas en MySQL Workbench.")

🗑️  Limpiando tabla Table_Goodreads si existe...
📤 Subiendo datos a Table_Goodreads...

C:\Users\cmoan\AppData\Local\Temp\ipykernel_17376\962716320.py:17: UserWarning: The provided table name 'Table_Goodreads' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  df.to_sql(table_name, con=engine, if_exists='append', index=False, chunksize=5000)

✅ Table_Goodreads subida con éxito.
🗑️  Limpiando tabla Table_Recommendations si existe...
📤 Subiendo datos a Table_Recommendations...

C:\Users\cmoan\AppData\Local\Temp\ipykernel_17376\962716320.py:17: UserWarning: The provided table name 'Table_Recommendations' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  df.to_sql(table_name, con=engine, if_exists='append', index=False, chunksize=5000)

✅ Table_Recommendations subida con éxito.
🗑️  Limpiando tabla Table_Amazon si existe...
📤 Subiendo datos a Table_Amazon...

C:\Users\cmoan\AppData\Local\Temp\ipykernel_17376\962716320.py:17: UserWarning: The provided table name 'Table_Amazon' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  df.to_sql(table_name, con=engine, if_exists='append', index=False, chunksize=5000)

✅ Table_Amazon subida con éxito.

✨ ¡PROCESO FINALIZADO! Ya puedes consultar tus tablas en MySQL Workbench.

In [66]:
# TITLE: High-Performance Categorization with Pandas (Final Version)
import pandas as pd
from sqlalchemy import create_engine
import pymysql

# 1. Database Connection Credentials
# Configuration: 'mysql+pymysql://USER:PASSWORD@HOST/DATABASE'
# Tip: If you don't have a password, leave it as :@localhost
USER = 'root'
PASSWORD = '18121996' 
HOST = 'localhost'
DATABASE = 'bookproject_db'

try:
    engine = create_engine(f'mysql+pymysql://{USER}:{PASSWORD}@{HOST}/{DATABASE}')
    
    # 2. Load data into DataFrames
    print("Connecting and loading data...")
    df_libros = pd.read_sql("SELECT * FROM dim_libros", engine)
    df_ratings = pd.read_sql("SELECT isbn FROM fact_ratings", engine)

    # 3. Logic: Identify low-impact books
    print("Analyzing relevance (Counting ratings)...")
    # We count how many times each ISBN appears in the ratings table
    rating_counts = df_ratings['isbn'].value_counts()
    
    # We create a set of ISBNs that move the needle (3+ ratings)
    priority_isbns = set(rating_counts[rating_counts >= 3].index)

    # 4. Categorization
    print("Applying 'Long Tail' category to low-impact records...")
    # Mask for books that are currently uncategorized
    is_empty = df_libros['categoria'].isna() | (df_libros['categoria'].isin(['', 'Sin Categoría']))
    
    # Mask for books NOT in the priority list
    is_low_impact = ~df_libros['isbn'].isin(priority_isbns)

    # Update: Uncategorized + Low Impact = Long Tail
    df_libros.loc[is_empty & is_low_impact, 'categoria'] = 'Long Tail'

    # 5. Write back to SQL
    print("Writing data back to MySQL (this replaces the table with updated data)...")
    # index=False prevents pandas from creating a new column for the index
    df_libros.to_sql('dim_libros', engine, if_exists='replace', index=False)

    print("Success! Process completed in seconds.")

except Exception as e:
    print(f"Error: {e}")

Connecting and loading data...
Analyzing relevance (Counting ratings)...
Applying 'Long Tail' category to low-impact records...
Writing data back to MySQL (this replaces the table with updated data)...
Success! Process completed in seconds.

In [68]:
# TITLE: Get remaining high-impact authors
import pandas as pd
from sqlalchemy import create_engine

# Conexión (Ajusta tus datos)
engine = create_engine('mysql+pymysql://root:18121996@localhost/bookproject_db')

# Solo cargamos los que siguen sin categoría (los que "rescatamos" antes)
print("Cargando autores pendientes de alta relevancia...")
df_pendientes = pd.read_sql("""
    SELECT autor, COUNT(*) as libros, SUM(votos) as impacto_votos
    FROM (
        SELECT l.autor, l.isbn, COUNT(r.puntuacion) as votos
        FROM dim_libros l
        JOIN fact_ratings r ON l.isbn = r.isbn
        WHERE l.categoria IS NULL OR l.categoria = '' OR l.categoria = 'Sin Categoría'
        GROUP BY l.autor, l.isbn
    ) AS sub
    GROUP BY autor
    ORDER BY impacto_votos DESC
""", engine)

print(df_pendientes)

Cargando autores pendientes de alta relevancia...
                                                autor  libros  impacto_votos
0                                         sue grafton      29         1989.0
1                                lilian jackson braun      44         1706.0
2                                     james patterson      24         1451.0
3                                           john saul      42         1251.0
4                                       iris johansen      28         1204.0
...                                               ...     ...            ...
18455                                  kimberli bryan       1            3.0
18456                                 ignacio ramonet       1            3.0
18457                                        tanazaki       1            3.0
18458                                      david mura       1            3.0
18459  siegfried engelmannphyllis haddoxelaine bruner       1            3.0

[18460 rows x 3 columns]

In [2]:
# TITLE: Open Library API Categorization - Strict Category Control
import pandas as pd
import requests
from sqlalchemy import create_engine
import time

# 1. Conexión a la base de datos
engine = create_engine('mysql+pymysql://root:18121996@localhost/bookproject_db')

# 2. Carga de autores de alto impacto sin categoría
print("Cargando autores prioritarios...")
query = """
    SELECT l.autor, COUNT(r.puntuacion) as impacto_votos
    FROM dim_libros l
    JOIN fact_ratings r ON l.isbn = r.isbn
    WHERE (l.categoria IS NULL OR l.categoria = '' OR l.categoria = 'Sin Categoría')
    GROUP BY l.autor
    ORDER BY impacto_votos DESC
    LIMIT 500
"""
df_authors = pd.read_sql(query, engine)

# 3. Mapeo Maestro: API Subjects -> TUS CATEGORÍAS
# He organizado tus categorías permitidas para que coincidan con los temas de la API
category_mapping = {
    'Fiction': ['detective', 'mystery', 'thriller', 'horror', 'suspense', 'crime'],
    'Science fiction': ['science fiction', 'space', 'aliens', 'robots', 'future'],
    'Novels': ['romance', 'love stories', 'contemporary', 'drama', 'saga'],
    'Literature': ['classic', 'poetry', 'anthology', 'literary', 'essays'],
    'Young': ['juvenile', 'children', 'teen', 'young adult', 'bedtime'],
    'Biography': ['biography', 'autobiography', 'memoir', 'journal'],
    'History': ['history', 'historical', 'archaeology', 'warfare'],
    'Religion': ['religion', 'christianity', 'bible', 'theology', 'spirituality'],
    'Science & Tech': ['science', 'technology', 'physics', 'math', 'computers', 'engineering'],
    'Political science': ['politics', 'government', 'international relations'],
    'Social sciences': ['sociology', 'anthropology', 'economics'],
    'Business': ['business', 'management', 'finance', 'marketing'],
    'Lifestyle': ['self-help', 'cookbook', 'recipes', 'health', 'diet', 'gardening'],
    'Travel': ['travel', 'tourism', 'geography', 'exploration'],
    'Psych': ['psychology', 'psychiatry', 'mental health'],
    'Art': ['art', 'painting', 'sculpture'],
    'Architecture': ['architecture', 'design'],
    'Theater': ['theater', 'plays', 'drama'],
    'Law': ['law', 'legal', 'justice'],
    'Education': ['education', 'teaching', 'school', 'textbook'],
    'Music': ['music', 'musical'],
    'Pets': ['pets', 'dogs', 'cats', 'animals'],
    'Languages': ['language', 'linguistics', 'grammar'],
    'Photography': ['photography', 'photo'],
    'No fiction': ['non-fiction', 'documentary']
}

def get_filtered_category(author_name):
    try:
        url = f"https://openlibrary.org/search/authors.json?q={author_name.replace(' ', '+')}"
        response = requests.get(url, timeout=10).json()
        
        if response.get('docs'):
            # Obtenemos los temas de la API
            api_subjects = [s.lower() for s in response['docs'][0].get('top_subjects', [])]
            
            # Buscamos coincidencia en tu lista permitida
            for api_sub in api_subjects:
                for target_cat, keywords in category_mapping.items():
                    if any(key in api_sub for key in keywords):
                        return target_cat
        return 'Other' # Si no hay match, usamos tu categoría 'Other'
    except:
        return None

# 4. Bucle de procesamiento
print(f"Consultando API para {len(df_authors)} autores...")
results = []

for index, row in df_authors.iterrows():
    author = row['autor']
    new_cat = get_filtered_category(author)
    if new_cat:
        results.append({'autor': author, 'nueva_categoria': new_cat})
        print(f"Asignado: {author} -> {new_cat}")
    
    time.sleep(0.6) # Delay para no saturar la API

# 5. Guardado en MySQL
if results:
    df_updates = pd.DataFrame(results)
    df_libros = pd

Cargando autores prioritarios...
Consultando API para 500 autores...
Asignado: sue grafton -> Fiction
Asignado: lilian jackson braun -> Fiction
Asignado: james patterson -> Fiction
Asignado: john saul -> Fiction
Asignado: iris johansen -> Fiction
Asignado: maeve binchy -> Novels
Asignado: johanna lindsey -> Novels
Asignado: toni morrison -> Young
Asignado: jeffery deaver -> Fiction
Asignado: faye kellerman -> Fiction
Asignado: tony hillerman -> Fiction
Asignado: anita shreve -> History
Asignado: julie garwood -> Fiction
Asignado: elizabeth berg -> Young
Asignado: michael connelly -> Fiction
Asignado: tami hoag -> Fiction
Asignado: nelson demille -> Fiction
Asignado: alice hoffman -> Young
Asignado: stuart woods -> Fiction
Asignado: belva plain -> History
Asignado: lavyrle spencer -> Novels
Asignado: kathy reichs -> Fiction
Asignado: janet evanovich -> Fiction
Asignado: Bill Bryson -> Travel
Asignado: barbara taylor bradford -> Novels
Asignado: sharyn mccrumb -> Fiction
Asignado: ann rule -> Biography
Asignado: douglas adams -> Science fiction
Asignado: jean m. auel -> History
Asignado: marian keyes -> Other
Asignado: david baldacci -> Fiction
Asignado: diane mott davidson -> Fiction
Asignado: neil gaiman -> Young
Asignado: elizabeth george -> Religion
Asignado: carl hiaasen -> Fiction
Asignado: anne rivers siddons -> Other
Asignado: scott turow -> Law
Asignado: jennifer crusie -> Novels
Asignado: nevada barr -> Fiction
Asignado: joy fielding -> Fiction
Asignado: robert jordan -> Other
Asignado: richard north patterson -> Law
Asignado: judith mcnaught -> Novels
Asignado: j.a. jance -> Other
Asignado: greg iles -> Fiction
Asignado: patricia daniels cornwell -> Fiction
Asignado: david eddings -> Other
Asignado: lisa scottoline -> Law
Asignado: jeffrey archer -> History
Asignado: sara paretsky -> Fiction
Asignado: christopher moore -> History
Asignado: tess gerritsen -> Fiction
Asignado: michael crichton -> Fiction
Asignado: minette walters -> Fiction
Asignado: william gibson -> Novels
Asignado: terry brooks -> Other
Asignado: richard bach -> Biography
Asignado: michael palmer -> Fiction
Asignado: heather graham -> Fiction
Asignado: clive barker -> Fiction
Asignado: ian mcewan -> Other
Asignado: olivia goldsmith -> Other
Asignado: anna quindlen -> Other
Asignado: jane smiley -> History
Asignado: barbara kingsolver -> Young
Asignado: l.m. montgomery -> Young
Asignado: kurt vonnegut -> Science fiction
Asignado: luanne rice -> Novels
Asignado: james herriot -> Biography
Asignado: adriana trigiani -> Novels
Asignado: lois lowry -> Young
Asignado: kay hooper -> Novels
Asignado: linda lael miller -> Novels
Asignado: lemony snicket -> Young
Asignado: jodi picoult -> Law
Asignado: j. d. robb -> Novels
Asignado: frank mccourt -> Biography
Asignado: lisa gardner -> Fiction
Asignado: gary larson -> Art
Asignado: douglas coupland -> Other
Asignado: chuck palahniuk -> Fiction
Asignado: jackie collins -> Fiction
Asignado: judith krantz -> Novels
Asignado: philip pullman -> Young
Asignado: louis sachar -> Young
Asignado: richard paul evans -> Young
Asignado: dale brown -> Fiction
Asignado: alice walker -> Young
Asignado: peter straub -> Fiction
Asignado: dave barry -> Young
Asignado: patricia cornwell -> Fiction
Asignado: amanda quick -> Other
Asignado: kaye gibbons -> History
Asignado: jasper fforde -> Fiction
Asignado: stephen coonts -> Fiction
Asignado: charlotte bronte -> Young
Asignado: james redfield -> Other
Asignado: brian jacques -> Young
Asignado: k. a. applegate -> Young
Asignado: scott adams -> Lifestyle
Asignado: isabel allende -> History
Asignado: karen robards -> Fiction
Asignado: barbara michaels -> Fiction
Asignado: meg cabot -> Young
Asignado: kristin hannah -> Novels
Asignado: erma bombeck -> Other
Asignado: kathleen e. woodiwiss -> Novels
Asignado: diana gabaldon -> Novels
Asignado: Terry Goodkind -> Other
Asignado: jack kerouac -> Literature
Asignado: tom robbins -> Biography
Asignado: ridley pearson -> Young
Asignado: joseph wambaugh -> Fiction
Asignado: mario puzo -> Fiction
Asignado: madeleine l'engle -> Young
Asignado: bill watterson -> Art
Asignado: tracy chevalier -> History
Asignado: steve martin -> Novels
Asignado: laurie r. king -> Fiction
Asignado: susan elizabeth phillips -> Novels
Asignado: f. scott fitzgerald -> Young
Asignado: john t. lescroart -> Fiction
Asignado: stephen white -> Fiction
Asignado: james lee burke -> Fiction
Asignado: colleen mccullough -> History
Asignado: jonathan franzen -> Literature
Asignado: carly phillips -> Novels
Asignado: maya angelou -> Literature
Asignado: sue miller -> Other
Asignado: lorna landvik -> Other
Asignado: susan isaacs -> Fiction
Asignado: dorothy gilman -> Fiction
Asignado: john gray -> Psych
Asignado: phillip margolin -> Fiction
Asignado: sheri s. tepper -> Science fiction
Asignado: caroline b. cooney -> Young
Asignado: connie willis -> Science fiction
Asignado: louise erdrich -> History
Asignado: jose saramago -> History
Asignado: donna tartt -> Other
Asignado: jane green -> Novels
Asignado: james clavell -> History
Asignado: tom wolfe -> Art
Asignado: martin cruz smith -> Fiction
Asignado: john jakes -> History
Asignado: douglas preston -> Fiction
Asignado: p. d. james -> Fiction
Asignado: neal stephenson -> History
Asignado: brad meltzer -> Biography
Asignado: arturo perez-reverte -> History
Asignado: christine feehan -> Novels
Asignado: peter hoeg -> History
Asignado: whitley strieber -> Science fiction
Asignado: lisa jackson -> Fiction
Asignado: ann brashares -> Young
Asignado: suzanne brockmann -> Novels
Asignado: arthur golden -> History
Asignado: michael jan friedman -> Science fiction
Asignado: barbara hambly -> Fiction
Asignado: tad williams -> Science fiction
Asignado: kevin j. anderson -> Science fiction
Asignado: fannie flagg -> Novels
Asignado: william goldman -> Theater
Asignado: christina dodd -> Novels
Asignado: stephen r. donaldson -> Science fiction
Asignado: nicholas evans -> Other
Asignado: cynthia voigt -> Young
Asignado: milan kundera -> History
Asignado: ayn rand -> Other
Asignado: mary jane clark -> Biography
Asignado: mary alice monroe -> Novels
Asignado: lynne reid banks -> Young
Asignado: john kennedy toole -> Art
Asignado: philippa gregory -> History
Asignado: katherine neville -> Other
Asignado: lisa kleypas -> Novels
Asignado: bill cosby -> Young
Asignado: lori foster -> Novels
Asignado: greg bear -> Science fiction
Asignado: jane feather -> Novels
Asignado: winston groom -> History
Asignado: perri o'shaughnessy -> Law
Asignado: christopher golden -> Young
Asignado: marcia muller -> Fiction
Asignado: tanya huff -> Science fiction
Asignado: garrison keillor -> Other
Asignado: diane duane -> Science fiction
Asignado: kim stanley robinson -> Science fiction
Asignado: bram stoker -> Fiction
Asignado: michael moore -> Biography
Asignado: dorothy allison -> Literature
Asignado: cormac mccarthy -> Other
Asignado: jane heller -> Novels
Asignado: iain pears -> Fiction
Asignado: mary daheim -> Fiction
Asignado: carol higgins clark -> Fiction
Asignado: john sandford -> Fiction
Asignado: robert james waller -> Photography
Asignado: sylvia plath -> Literature
Asignado: scott o'dell -> Young
Asignado: erica spindler -> Fiction
Asignado: kazuo ishiguro -> History
Asignado: robert crais -> Other
Asignado: ben elton -> Novels
Asignado: maggie shayne -> Novels
Asignado: sue townsend -> Other
Asignado: david sedaris -> Literature
Asignado: nick bantock -> Other
Asignado: judith michael -> Novels
Asignado: harlan coben -> Fiction
Asignado: susan cooper -> Young
Asignado: bentley little -> Fiction
Asignado: louise rennison -> Young
Asignado: brenda joyce -> Novels
Asignado: mary stewart -> Novels
Asignado: al franken -> Political science
Asignado: steven paul martini -> Other
Asignado: charles de lint -> Young
Asignado: anne frank -> History
Asignado: sophie kinsella -> Novels
Asignado: john j. nance -> Fiction
Asignado: patrick suskind -> Fiction
Asignado: david brin -> Science fiction
Asignado: philip roth -> Other
Asignado: peter mayle -> Other
Asignado: zora neale hurston -> Novels
Asignado: nicholas sparks -> Novels
Asignado: bret easton ellis -> Other
Asignado: susan wiggs -> Novels
Asignado: paulo coelho -> Young
Asignado: joanne harris -> Other
Asignado: joseph heller -> Other
Asignado: walter mosley -> Fiction
Asignado: ann packer -> Other
Asignado: dorothy garlock -> Novels
Asignado: stella cameron -> Novels
Asignado: robin mckinley -> Other
Asignado: timothy zahn -> Science fiction
Asignado: joan johnston -> Novels
Asignado: william diehl -> Fiction
Asignado: len deighton -> Fiction
Asignado: dan simmons -> Science fiction
Asignado: stephanie laurens -> Novels
Asignado: eileen goudge -> Other
Asignado: vc andrews -> Fiction
Asignado: katherine kurtz -> Other
Asignado: steve martini -> Law
Asignado: edward rutherfurd -> History
Asignado: jean craighead george -> Young
Asignado: ian rankin -> Fiction
Asignado: alessandro baricco -> History
Asignado: wendy holden -> Biography
Asignado: dennis lehane -> Fiction
Asignado: l. ron hubbard -> Science fiction
Asignado: v. c. andrews -> Fiction
Asignado: robert harris -> Science & Tech
Asignado: robert k. tanenbaum -> Law
Asignado: david morrell -> Fiction
Asignado: ann b. ross -> Other
Asignado: mary jo putney -> Novels
Asignado: leo tolstoy -> Other
Asignado: david lodge -> History
Asignado: bertrice small -> History
Asignado: robert r mccammon -> Fiction
Asignado: lloyd alexander -> Young
Asignado: linda fairstein -> Fiction
Asignado: nancy martin -> Fiction
Asignado: ira levin -> Science fiction
Asignado: gail tsukiyama -> History
Asignado: sharon sala -> Fiction
Asignado: william faulkner -> Other
Asignado: rosemary rogers -> Novels
Asignado: susan wittig albert -> Fiction
Asignado: leigh nicholsdean koontz -> Other
Asignado: charlaine harris -> Fiction
Asignado: jo beverley -> Novels
Asignado: whitney otto -> Photography
Asignado: donna leon -> Fiction
Asignado: kasey michaels -> Novels
Asignado: robertson davies -> History
Asignado: ken kesey -> Other
Asignado: nancy taylor rosenberg -> Fiction
Asignado: cleveland amory -> Biography
Asignado: teresa medeiros -> Novels
Asignado: myla goldberg -> Novels
Asignado: salman rushdie -> Other
Asignado: melinda haynes -> Young
Asignado: nicci french -> Fiction
Asignado: geraldine brooks -> Biography
Asignado: e. b. white -> Young
Asignado: henning mankell -> Fiction
Asignado: victoria holt -> Other
Asignado: jill churchill -> Fiction
Asignado: patricia gaffney -> Novels
Asignado: thomas keneally -> History
Asignado: bruce coville -> Young
Asignado: herman wouk -> Novels
Asignado: george eliot -> Other
Asignado: r. a. salvatore -> Other
Asignado: michael ondaatje -> Literature
Asignado: joan hess -> Fiction
Asignado: annie proulx -> History
Asignado: carol shields -> Other
Asignado: david guterson -> Young
Asignado: nancy pickard -> Fiction
Asignado: kate atkinson -> Fiction
Asignado: carolyn g. hart -> Fiction
Asignado: chaim potok -> Other
Asignado: joann ross -> Novels
Asignado: Fyodor Dostoevsky -> Other
Asignado: lorenzo carcaterra -> Other
Asignado: w. michael gear -> History
Asignado: candace bushnell -> Young
Asignado: robert pirsig -> Other
Asignado: m. c. beaton -> Fiction
Asignado: frank e. peretti -> Young
Asignado: joanna trollope -> Novels
Asignado: lois duncan -> Young
Asignado: arthur hailey -> Fiction
Asignado: raymond e. feist -> Other
Asignado: richard laymon -> Fiction
Asignado: frances mayes -> Travel
Asignado: dave pelzer -> Biography
Asignado: j.d. salinger -> Other
Asignado: margaret maron -> Fiction
Asignado: haruki murakami -> Literature
Asignado: kathleen o'neal gear -> Other
Asignado: avi -> Young
Asignado: kate wilhelm -> Science fiction
Asignado: catherine anderson -> Novels
Asignado: rohinton mistry -> Art
Asignado: terry mcmillan -> Other
Asignado: marge piercy -> Literature
Asignado: shannon drake -> Novels
Asignado: john darnton -> Fiction
Asignado: jerry seinfeld -> Young
Asignado: jhumpa lahiri -> Biography
Asignado: wilbur smith -> History
Asignado: colin dexter -> Fiction
Asignado: deborah smith -> Novels
Asignado: john case -> Fiction
Asignado: ursula hegi -> History
Asignado: morgan llywelyn -> History
Asignado: haven kimmel -> Fiction
Asignado: barbara parker -> Fiction
Asignado: harry turtledove -> Science fiction
Asignado: val mcdermid -> Fiction
Asignado: katherine applegate -> Young
Asignado: sandra cisneros -> Literature
Asignado: sylvia nasar -> Science & Tech
Asignado: lalita tademy -> Novels
Asignado: sandra hill -> Novels
Asignado: mary karr -> Biography
Asignado: carson mccullers -> Novels
Asignado: robert j. sawyer -> Science fiction
Asignado: Daphne du Maurier -> History
Asignado: julia alvarez -> Young
Asignado: tim o'brien -> Travel
Asignado: billie letts -> Young
Asignado: raymond feist -> Other
Asignado: garth nix -> Young
Asignado: sarah ban breathnach -> Psych
Asignado: pat conroy -> Biography
Asignado: lynne truss -> Languages
Asignado: sheri holman -> Other
Asignado: h. g. wells -> Science fiction
Asignado: julia quinn -> Novels
Asignado: jimmy buffett -> Music
Asignado: william shatner -> Science fiction
Asignado: dorothea benton frank -> Other
Asignado: meggin cabot -> Other
Asignado: alex garland -> Fiction
Asignado: kat martin -> Fiction
Asignado: bernard cornwell -> History
Asignado: jerry spinelli -> Young
Asignado: brian lumley -> Fiction
Asignado: susan andersen -> Novels
Asignado: anonymous -> History
Asignado: erich segal -> History
Asignado: todd strasser -> Young
Asignado: dr. seuss -> Young
Asignado: olive ann burns -> History
Asignado: barbara park -> Young
Asignado: sarah mlynowski -> Young
Asignado: arthur miller -> Novels
Asignado: joanna cole -> Young
Asignado: willa cather -> History
Asignado: richard russo -> Other
Asignado: jennifer blake -> Novels
Asignado: katherine stone -> Novels
Asignado: david weber -> Science fiction
Asignado: lynn kurland -> Travel
Asignado: iain banks -> Music
Asignado: dominick dunne -> Law
Asignado: william styron -> Biography
Asignado: wilbur a. smith -> Travel
Asignado: howard fast -> History
Asignado: janet evanovichlorelei king -> Other
Asignado: guy gavriel kay -> History
Asignado: lee smith -> Young
Asignado: diane johnson -> Travel
Asignado: stephen hunter -> Fiction
Asignado: allan folsom -> Political science
Asignado: alex kava -> Fiction
Asignado: leslie glass -> Other
Asignado: e. l. doctorow -> History
Asignado: sherryl woods -> Novels
Asignado: diane carey -> Science fiction
Asignado: lee child -> Fiction
Asignado: james joyce -> Young
Asignado: wendy northcutt -> Literature
Asignado: john fowles -> History
Asignado: lurlene mcdaniel -> Young
Asignado: tina wainscott -> Novels
Asignado: chitra banerjee divakaruni -> History
Asignado: richard bachman -> Other
Asignado: john dunning -> Fiction
Asignado: t. coraghessan boyle -> History
Asignado: melanie rawn -> Science fiction
Asignado: katherine paterson -> Young
Asignado: spider robinson -> Science fiction
Asignado: roger zelazny -> Young
Asignado: nuala o'faolain -> Biography
Asignado: john updike -> Literature
Asignado: noah gordon -> History
Asignado: jennifer roberson -> History
Asignado: robert fulghum -> Other
Asignado: jonathan harr -> Law
Asignado: helene hanff -> Biography
Asignado: barbara vine -> Fiction
Asignado: virginia henley -> Novels
Asignado: debbie dadey -> Young
Asignado: marie ferrarella -> Novels
Asignado: janelle taylor -> Novels
Asignado: j. f. freedman -> Fiction
Asignado: dav pilkey -> Young
Asignado: arlene eisenberg -> Other
Asignado: wilson rawls -> Young
Asignado: Victor Hugo -> History
Asignado: mary higgins clarkcarol higgins clark -> Other
Asignado: roddy doyle -> Young
Asignado: don delillo -> Other
Asignado: bob greene -> Lifestyle
Asignado: martin h. greenberg -> Science fiction
Asignado: jacquelyn mitchard -> Young
Asignado: charles grant -> Fiction
Asignado: leon uris -> History
Asignado: karen kijewski -> Fiction
Asignado: hunter s. thompson -> Biography
Asignado: karen harper -> Fiction
Asignado: tamora pierce -> Young
Asignado: laura zigman -> Other
Asignado: sena jeter naslund -> History
Asignado: kyle mills -> Fiction
Asignado: karin slaughter -> Fiction
Asignado: jim wilson -> Religion
Asignado: james herbert -> Fiction
Asignado: truman capote -> Young
Asignado: daniel silva -> Fiction
Asignado: michael lee west -> Fiction
Asignado: beth gutcheon -> Novels
Asignado: sharon creech -> Young
Asignado: tom sharpe -> Other
Asignado: gail godwin -> Other
Asignado: carla neggers -> Fiction
Asignado: christian jacq -> History
Asignado: john lescroart -> Law
Asignado: frances hodgson burnett -> Young
Asignado: sandra dallas -> History
Asignado: f. paul wilson -> Fiction
Asignado: t. jefferson parker -> Fiction
Asignado: gaston leroux -> Fiction
Asignado: stephen j. cannell -> Fiction
Asignado: mary balogh -> Novels
Asignado: jennifer chiaverini -> Other
Asignado: susan vreeland -> Art
Asignado: stan redding -> Biography
Asignado: amanda cross -> Fiction
Asignado: mary lynn baxter -> Novels
Asignado: anne george -> Fiction
Asignado: connie mason -> Novels
Asignado: David McCullough -> History
Asignado: reginald hill -> Fiction
Asignado: ann patchett -> Other
Asignado: vince flynn -> Fiction
Asignado: judy collins -> Biography
Asignado: peter benchley -> Art
Asignado: richard matheson -> Fiction
Asignado: john knowles -> Education
Asignado: sylvia browne -> Science fiction
Asignado: peter robinson -> Fiction
Asignado: anne lamott -> Biography
Asignado: carol o'connell -> Other
Asignado: d. h. lawrence -> Law
Asignado: donna woolfolk cross -> Languages
Asignado: elizabeth strout -> Other
Asignado: francine rivers -> History
Asignado: norman bridwell -> Young
Asignado: elinor lipman -> Other
Asignado: Daniel Defoe -> Political science

In [3]:
# TITLE: Diagnostic of the 45k Uncategorized Records
import pandas as pd
from sqlalchemy import create_engine
from collections import Counter
import re

# 1. Database Connection
engine = create_engine('mysql+pymysql://root:18121996@localhost/bookproject_db')

# 2. Load only the uncategorized rows
print("Cargando datos pendientes...")
query = """
    SELECT autor, titulo 
    FROM dim_libros 
    WHERE categoria IS NULL OR categoria = '' OR categoria = 'Sin Categoría'
"""
df_pending = pd.read_sql(query, engine)

# 3. Analysis: Top Authors
top_authors = df_pending['autor'].value_counts().head(20)

# 4. Analysis: Most Common Words in Titles (Cleaning noise)
def clean_titles(text):
    # Remove special characters and common stop words
    text = re.sub(r'[^\w\s]', '', str(text).lower())
    words = text.split()
    # Filter out very short words (the, a, in, of...)
    return [w for w in words if len(w) > 3]

all_words = []
df_pending['titulo'].apply(lambda x: all_words.extend(clean_titles(x)))
common_words = Counter(all_words).most_common(20)

# 5. Show Results
print("\n--- TOP 20 AUTORES SIN CATEGORÍA ---")
print(top_authors)

print("\n--- TOP 20 PALABRAS EN TÍTULOS ---")
for word, freq in common_words:
    print(f"{word}: {freq}")

Cargando datos pendientes...

--- TOP 20 AUTORES SIN CATEGORÍA ---
autor
johanna lindsey            44
jackie collins             44
lilian jackson braun       44
linda lael miller          43
k. a. applegate            42
jeffrey archer             42
john saul                  42
douglas adams              41
heather graham             38
stuart woods               37
bertrice small             37
clive barker               37
barbara taylor bradford    37
tony hillerman             36
alice hoffman              36
christopher golden         34
joan hess                  34
michael jan friedman       33
joy fielding               33
dorothy gilman             33
Name: count, dtype: int64

--- TOP 20 PALABRAS EN TÍTULOS ---
novel: 1951
book: 1880
harlequin: 1717
love: 981
romance: 967
mystery: 947
life: 878
paperback: 837
mysteries: 787
from: 737
classics: 702
stories: 699
story: 684
series: 620
american: 613
your: 592
star: 589
time: 496
world: 489
guide: 488

In [4]:
# TITLE: Second Pass - Deep Search API for remaining 45k
import pandas as pd
import requests
import time
from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://root:18121996@localhost/bookproject_db')

# 1. Cargamos los 45k que quedaron vacíos
print("Cargando registros pendientes...")
df_pending = pd.read_sql("SELECT isbn, autor, titulo FROM dim_libros WHERE categoria IS NULL OR categoria = '' OR categoria = 'Sin Categoría'", engine)

# Usaremos el mismo mapa de categorías que definimos antes
category_mapping = {
    'Fiction': ['detective', 'mystery', 'thriller', 'horror', 'suspense', 'crime'],
    'Science fiction': ['science fiction', 'space', 'star trek', 'star wars', 'fantasy'],
    'Novels': ['romance', 'love stories', 'contemporary', 'drama', 'saga', 'harlequin'],
    'Literature': ['classic', 'poetry', 'anthology', 'literary'],
    'Young': ['juvenile', 'children', 'teen', 'young adult'],
    'No fiction': ['history', 'biography', 'science', 'politics', 'philosophy']
}

def deep_search_api(row):
    # Intentamos primero por autor, si falla, por título
    queries = [
        f"https://openlibrary.org/search/authors.json?q={row['autor'].replace(' ', '+')}",
        f"https://openlibrary.org/search.json?title={row['titulo'].replace(' ', '+')}&limit=1"
    ]
    
    for url in queries:
        try:
            response = requests.get(url, timeout=5).json()
            docs = response.get('docs', [])
            if docs:
                subjects = [s.lower() for s in docs[0].get('top_subjects', docs[0].get('subject', []))]
                for sub in subjects:
                    for target_cat, keywords in category_mapping.items():
                        if any(key in sub for key in keywords):
                            return target_cat
            time.sleep(0.4) # Pausa mínima para no ser bloqueados
        except:
            continue
    return None

# 2. Procesamos (Vamos a probar con un bloque de 1000 para ver efectividad)
print("Iniciando búsqueda profunda en API...")
# Para la prueba final, podrías quitar el .head(1000)
df_sample = df_pending.head(1000).copy() 

df_sample['categoria_nueva'] = df_sample.apply(deep_search_api, axis=1)

# 3. Ver resultados del intento
exito = df_sample['categoria_nueva'].notna().sum()
print(f"Resultado: Logramos categorizar {exito} de 1000 registros analizados.")

# 4. Guardado parcial (opcional)
# Aquí seguiríamos la misma lógica de guardado que antes

Cargando registros pendientes...
Iniciando búsqueda profunda en API...
Resultado: Logramos categorizar 731 de 1000 registros analizados.

In [2]:
# TITLE: Final Mass Update - Deep Search API with Persistence
import pandas as pd
import requests
import time
import sys
from sqlalchemy import create_engine
from tqdm import tqdm  # Para ver la barra de progreso real

# 1. Database Connection
engine = create_engine('mysql+pymysql://root:18121996@localhost/bookproject_db')

# 2. Load pending records
print("Cargando registros pendientes...")
df_pending = pd.read_sql("SELECT isbn, autor, titulo FROM dim_libros WHERE categoria IS NULL OR categoria = '' OR categoria = 'Sin Categoría'", engine)

if df_pending.empty:
    print("¡No hay registros pendientes!")
    sys.exit()

# Mapping configuration (Keep your strict list)
category_mapping = {
    'Fiction': ['detective', 'mystery', 'thriller', 'horror', 'suspense', 'crime'],
    'Science fiction': ['science fiction', 'space', 'aliens', 'robots', 'future'],
    'Novels': ['romance', 'love stories', 'contemporary', 'drama', 'saga'],
    'Literature': ['classic', 'poetry', 'anthology', 'literary', 'essays'],
    'Young': ['juvenile', 'children', 'teen', 'young adult', 'bedtime'],
    'Biography': ['biography', 'autobiography', 'memoir', 'journal'],
    'History': ['history', 'historical', 'archaeology', 'warfare'],
    'Religion': ['religion', 'christianity', 'bible', 'theology', 'spirituality'],
    'Science & Tech': ['science', 'technology', 'physics', 'math', 'computers', 'engineering'],
    'Political science': ['politics', 'government', 'international relations'],
    'Social sciences': ['sociology', 'anthropology', 'economics'],
    'Business': ['business', 'management', 'finance', 'marketing'],
    'Lifestyle': ['self-help', 'cookbook', 'recipes', 'health', 'diet', 'gardening'],
    'Travel': ['travel', 'tourism', 'geography', 'exploration'],
    'Psych': ['psychology', 'psychiatry', 'mental health'],
    'Art': ['art', 'painting', 'sculpture'],
    'Architecture': ['architecture', 'design'],
    'Theater': ['theater', 'plays', 'drama'],
    'Law': ['law', 'legal', 'justice'],
    'Education': ['education', 'teaching', 'school', 'textbook'],
    'Music': ['music', 'musical'],
    'Pets': ['pets', 'dogs', 'cats', 'animals'],
    'Languages': ['language', 'linguistics', 'grammar'],
    'Photography': ['photography', 'photo'],
    'No fiction': ['non-fiction', 'documentary']
}

def deep_search_api(row):
    queries = [
        f"https://openlibrary.org/search/authors.json?q={row['autor'].replace(' ', '+')}",
        f"https://openlibrary.org/search.json?title={row['titulo'].replace(' ', '+')}&limit=1"
    ]
    for url in queries:
        try:
            response = requests.get(url, timeout=5).json()
            docs = response.get('docs', [])
            if docs:
                subjects = [s.lower() for s in docs[0].get('top_subjects', docs[0].get('subject', []))]
                for sub in subjects:
                    for target_cat, keywords in category_mapping.items():
                        if any(key in sub for key in keywords):
                            return target_cat
            time.sleep(0.4)
        except:
            continue
    return None

# 3. Processing with Progress Bar
print(f"Iniciando categorización de {len(df_pending)} registros...")
tqdm.pandas() # Habilita la barra de progreso para .apply()

df_pending['categoria_nueva'] = df_pending.progress_apply(deep_search_api, axis=1)

# 4. Merging and Persistence
print("\nPersistiendo cambios en MySQL...")
# Cargamos la tabla completa para actualizarla
df_full = pd.read_sql("SELECT * FROM dim_libros", engine)

# Creamos un diccionario de mapeo {isbn: categoria_nueva}
updates = df_pending.dropna(subset=['categoria_nueva']).set_index('isbn')['categoria_nueva'].to_dict()

# Aplicamos las actualizaciones
df_full['categoria'] = df_full.apply(
    lambda x: updates.get(x['isbn'], x['categoria']), axis=1
)

# 5. Overwrite the table in MySQL
df_full.to_sql('dim_libros', engine, if_exists='replace', index=False)

print(f"¡Proceso finalizado! Se han rescatado {len(updates)} libros.")

Cargando registros pendientes...
Iniciando categorización de 45411 registros...

100%|██████████| 45411/45411 [9:52:03<00:00,  1.28it/s]

Persistiendo cambios en MySQL...

PendingRollbackError: Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)

In [3]:
# TITLE: Emergency Save - Re-establishing Connection
from sqlalchemy import create_engine

# 1. Creamos una conexión nueva y fresca
engine_new = create_engine('mysql+pymysql://root:18121996@localhost/bookproject_db')

try:
    print("Recuperando datos de la memoria...")
    # Recuperamos la tabla completa con la nueva conexión
    df_full = pd.read_sql("SELECT * FROM dim_libros", engine_new)
    
    # Creamos el diccionario con lo que ya procesaste (df_pending sigue vivo en memoria)
    updates = df_pending.dropna(subset=['categoria_nueva']).set_index('isbn')['categoria_nueva'].to_dict()
    
    print(f"Aplicando {len(updates)} actualizaciones...")
    df_full['categoria'] = df_full.apply(
        lambda x: updates.get(x['isbn'], x['categoria']), axis=1
    )
    
    # 2. Guardamos con la conexión nueva
    df_full.to_sql('dim_libros', engine_new, if_exists='replace', index=False)
    print("¡DATOS SALVADOS CON ÉXITO en MySQL!")

except Exception as e:
    print(f"Error al salvar: {e}")
    # Si esto falla, guarda al menos un CSV de emergencia para no perder las 10 horas
    df_pending.to_csv("backup_recuperacion_10horas.csv", index=False)
    print("Se ha guardado un CSV de emergencia llamado 'backup_recuperacion_10horas.csv'")

Recuperando datos de la memoria...
Aplicando 38903 actualizaciones...
Error al salvar: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Se ha guardado un CSV de emergencia llamado 'backup_recuperacion_10horas.csv'

In [4]:
# TITLE: Final Step - Uploading the Saved Backup to MySQL
import pandas as pd
from sqlalchemy import create_engine

# 1. Creamos una conexión limpia
engine_final = create_engine('mysql+pymysql://root:18121996@localhost/bookproject_db')

# 2. Cargamos el backup que acabas de crear
print("Cargando el archivo de emergencia...")
df_backup = pd.read_csv("backup_recuperacion_10horas.csv")

# 3. Cargamos la tabla original para hacer el cruce final
print("Preparando la tabla completa...")
df_full = pd.read_sql("SELECT * FROM dim_libros", engine_final)

# 4. Actualizamos las categorías
updates = df_backup.dropna(subset=['categoria_nueva']).set_index('isbn')['categoria_nueva'].to_dict()
df_full['categoria'] = df_full.apply(lambda x: updates.get(x['isbn'], x['categoria']), axis=1)

# 5. Limpieza final: Todo lo que siga vacío va a 'Other'
df_full['categoria'] = df_full['categoria'].replace(['', 'Sin Categoría', None], 'Other')

# 6. Subida definitiva
print("Subiendo datos finales a MySQL (esto tardará unos 5 min)...")
df_full.to_sql('dim_libros', engine_final, if_exists='replace', index=False)

print("¡PROYECTO COMPLETADO! Ya puedes ir a Power BI.")

Cargando el archivo de emergencia...
Preparando la tabla completa...
Subiendo datos finales a MySQL (esto tardará unos 5 min)...
¡PROYECTO COMPLETADO! Ya puedes ir a Power BI.

In [1]:
# TITLE: FINAL RESCUE - Total Visibility Mode
import pandas as pd
from sqlalchemy import create_engine, text
import requests

engine = create_engine('mysql+pymysql://root:18121996@localhost/bookproject_db')

query = """
    SELECT l.isbn, l.titulo 
    FROM dim_libros l
    JOIN fact_ratings r ON l.isbn = r.isbn
    WHERE l.categoria = 'Long Tail'
    GROUP BY l.isbn, l.titulo
    HAVING COUNT(r.puntuacion) >= 2
    ORDER BY COUNT(r.puntuacion) DESC
    LIMIT 5000;
"""

print("🚀 Iniciando... Si ves esto, el código está vivo.", flush=True)
df_top = pd.read_sql(query, engine)

if not df_top.empty:
    print(f"📦 {len(df_top)} libros detectados. Empezamos:", flush=True)
    for i, row in df_top.iterrows():
        try:
            url = f"https://openlibrary.org/api/books?bibkeys=ISBN:{row['isbn']}&format=json&jscmd=data"
            r = requests.get(url, timeout=5).json()
            key = f"ISBN:{row['isbn']}"
            
            nueva_cat = r[key]['subjects'][0]['name'] if key in r and 'subjects' in r[key] else None
            
            if nueva_cat:
                with engine.begin() as conn:
                    stmt = text("UPDATE dim_libros SET categoria = :cat WHERE isbn = :isbn")
                    conn.execute(stmt, {"cat": nueva_cat, "isbn": row['isbn']})
                print(f"✅ [{i+1}] Rescatado: {row['titulo'][:30]}... -> {nueva_cat}", flush=True)
            else:
                # Si no hay categoría, imprimimos un punto para saber que sigue trabajando
                print(".", end="", flush=True)
                
        except Exception:
            print("x", end="", flush=True) # Una 'x' si falla la conexión de ese libro
            continue

🚀 Iniciando... Si ves esto, el código está vivo.
📦 5000 libros detectados. Empezamos:
✅ [1] Rescatado: blossoms and the green phantom... -> Family life
.✅ [3] Rescatado: the new world spanish-english ... -> English
✅ [4] Rescatado: theo and me (get into the groo... -> Adolescence
✅ [5] Rescatado: 100 years of american newspape... -> History and criticism
✅ [6] Rescatado: what do you know?... -> Questions and answers
✅ [7] Rescatado: just plain cat... -> Schools
✅ [8] Rescatado: spoken spanish for students an... -> Spoken Spanish
✅ [9] Rescatado: michael jordan: a biography... -> African Americans
✅ [10] Rescatado: assorted foxtrot... -> Humor, form, comic strips & cartoons
✅ [11] Rescatado: unger's bible handbook... -> Bible
✅ [12] Rescatado: great people of the bible and ... -> Bible
✅ [13] Rescatado: jacob: the fools god chooses... -> Bible
.✅ [15] Rescatado: santa paws and the new puppy (... -> Juvenile fiction
✅ [16] Rescatado: alas babylon... -> Survival
✅ [17] Rescatado: what if . . .... -> Visualization
✅ [18] Rescatado: the story of vajont (crossings... -> Drama
..✅ [21] Rescatado: youngblood hawke... -> Publishers and publishing
✅ [22] Rescatado: endless knot: book three of th... -> Mythology, Celtic
✅ [23] Rescatado: hidden truth... -> Fantasy
✅ [24] Rescatado: forgotten truth... -> American Fantasy fiction
.✅ [26] Rescatado: hollywood cats... -> Cats in motion pictures
✅ [27] Rescatado: nine stories... -> Fiction
✅ [28] Rescatado: checklist for a perfect weddin... -> Family & Relationships
✅ [29] Rescatado: don't fence me in (man of the ... -> Actors
✅ [30] Rescatado: dr. ruth's guide for married l... -> Sex in marriage
✅ [31] Rescatado: the people magazine guide to m... -> Reviews
✅ [32] Rescatado: the mummy, the will, and the c... -> Johnny Dixon (Fictitious character)
✅ [33] Rescatado: how to talk to your cat... -> Human-animal communication
✅ [34] Rescatado: dracula (enriched classics ser... -> English literature
✅ [35] Rescatado: ninety-two in the shade (conte... -> Florida, fiction
✅ [36] Rescatado: stancliffe's hotel (penguin cl... -> Angria (Imaginary place)
✅ [37] Rescatado: und die eselin sah den engel. ... -> Behinderter Mensch
✅ [38] Rescatado: the centurion: an historical n... -> Fiction, general
✅ [39] Rescatado: demonic males apes and the ori... -> Aggressive behavior in animals
...✅ [43] Rescatado: resumes for dummies... -> Job hunting
✅ [44] Rescatado: ramses 3: the battle of kadesh... -> Literature and fiction, historical fiction
✅ [45] Rescatado: keeper of the house... -> Fiction
✅ [46] Rescatado: morbid symptoms (pluto crime)... -> Fiction, mystery & detective, general
✅ [47] Rescatado: icebreaker... -> Fiction
✅ [48] Rescatado: the fourth frontier exploring ... -> Christian Stewardship
✅ [49] Rescatado: a woman's path... -> Women in the professions
✅ [50] Rescatado: feather crowns... -> Fiction
✅ [51] Rescatado: keeper of the crystal spring... -> Fiction, historical, general
✅ [52] Rescatado: the song of the tide... -> Cousins -- Fiction
✅ [53] Rescatado: leaving : a novel... -> African American families
✅ [54] Rescatado: newfangled : a novel... -> Man-woman relationships
✅ [55] Rescatado: zip goes zebra (sweet pickles ... -> Juvenile fiction
✅ [56] Rescatado: the struggle (the vampire diar... -> Children's fiction
✅ [57] Rescatado: i.o.u.... -> Children's fiction
✅ [58] Rescatado: aunt eater loves a mystery (i ... -> Children's fiction
✅ [59] Rescatado: x files ya #12 grotesque (x fi... -> Children's fiction
✅ [60] Rescatado: moon over minneapolis... -> Fiction, general
✅ [61] Rescatado: deep doo-doo... -> Television broadcasting
✅ [62] Rescatado: loudmouth george and the corne... -> Bands (Music)
✅ [63] Rescatado: don't look back... -> Fiction
✅ [64] Rescatado: big bird's red book... -> Color, juvenile literature
✅ [65] Rescatado: what does baby mickey find? (d... -> Babies
✅ [66] Rescatado: henrietta and the hat (golden ... -> Fiction
✅ [67] Rescatado: snoopy's book of colors (golde... -> Color
✅ [68] Rescatado: the eensy weensy spider (golde... -> Nursery rhymes
✅ [69] Rescatado: the young indiana jones chroni... -> Mummies
✅ [70] Rescatado: disney's aladdin: monkey busin... -> Arab countries
✅ [71] Rescatado: toy story 2 (look-look book)... -> Collectors and collecting
✅ [72] Rescatado: kiss of the vampire... -> Vampires
✅ [73] Rescatado: rebel rebel (girl talk)... -> Children: Babies Toddlers
✅ [74] Rescatado: stealing the show (girl talk)... -> School plays
✅ [75] Rescatado: peter pan (sight &amp; sound)... -> Fantasy
✅ [76] Rescatado: i can count (i can count)... -> Juvenile literature
✅ [77] Rescatado: arthur's valentine (arthur adv... -> Children: Kindergarten
✅ [78] Rescatado: the forest people (picador)... -> Ethnology
✅ [79] Rescatado: the russians... -> Social life and customs
..✅ [82] Rescatado: empire of unreason (age of unr... -> Fiction
.✅ [84] Rescatado: mornings a seven (harlequin de... -> Fiction, general
✅ [85] Rescatado: man from cougar pass (silhouet... -> Fiction, general
✅ [86] Rescatado: at risk (silhouette intimate m... -> Fiction, general
✅ [87] Rescatado: another man's wife (heartbreak... -> Widows
✅ [88] Rescatado: risk of the heart (harlequin p... -> Fiction, general
✅ [89] Rescatado: second mrs adams  (top author)... -> Accidents
✅ [90] Rescatado: baby bond (his baby) (presents... -> Fiction
✅ [91] Rescatado: sarabande (harlequin intrigue ... -> Fiction, general
✅ [92] Rescatado: i am a gymnast (young dreamers... -> Foster, McKenzie
✅ [93] Rescatado: eye of the beholder (an avon f... -> Children's fiction
✅ [94] Rescatado: russian journal... -> Social conditions
✅ [95] Rescatado: there he goes again: ronald re... -> Politics and government
✅ [96] Rescatado: aeneid... -> Poetry
✅ [97] Rescatado: puppy peek-a-boo (peek-a-board... -> Fiction
✅ [98] Rescatado: meet babar and his family... -> Elephants
✅ [99] Rescatado: the mystery of the pirate ghos... -> Children's stories, American
✅ [100] Rescatado: at the playground (sesame stre... -> Puppets
✅ [101] Rescatado: great day for up (a bright &am... -> Stories in rhyme
✅ [102] Rescatado: penance (holland taylor myster... -> Fiction
✅ [103] Rescatado: surf's up, pikachu! (pokã©mon ... -> Surfing
✅ [104] Rescatado: 13 scary ghost stories... -> Ghosts
✅ [105] Rescatado: the trident tragedy... -> Thriller
✅ [106] Rescatado: letters from a stranger... -> Pen pals
✅ [107] Rescatado: the story of daniel boone, wil... -> Juvenile literature
✅ [108] Rescatado: funny bananas... -> Fiction
✅ [109] Rescatado: have you seen hyacinth macaw?... -> City and town life
✅ [110] Rescatado: something queer on vacation... -> Juvenile fiction
✅ [111] Rescatado: beezus and ramona... -> readers
.✅ [113] Rescatado: unnatural causes... -> Fiction
✅ [114] Rescatado: murder unprompted... -> Actors
✅ [115] Rescatado: haywire... -> Fiction, psychological
.✅ [117] Rescatado: the improper playwright (signe... -> Fiction, Romance, Historical, Regency
✅ [118] Rescatado: pancakes, crackers and pizza: ... -> Children's fiction
✅ [119] Rescatado: philadelphia: a picture book t... -> Pictorial works
✅ [120] Rescatado: act of god... -> Fiction in English
✅ [121] Rescatado: castaways on long ago... -> Brothers and sisters
.✅ [123] Rescatado: sundiver (uplift trilogy)... -> Uplift
✅ [124] Rescatado: mystery/senke # 44... -> Fiction
✅ [125] Rescatado: through the wall... -> Fiction, mystery & detective, women sleuths
✅ [126] Rescatado: cave of time... -> Plot-your-own stories
.✅ [128] Rescatado: the bannerman solution... -> Paul Bannerman (Fictitious character)
..✅ [131] Rescatado: encyclopedia brown and the cas... -> Mystery and detective stories
✅ [132] Rescatado: monster jam (bbc radio present... -> Juvenile fiction
✅ [133] Rescatado: rudy: a true story... -> Football players
✅ [134] Rescatado: totally taylor: hansons's hear... -> Rock groups
✅ [135] Rescatado: clifford's spring clean-up (cl... -> Cleaning
✅ [136] Rescatado: quake!... -> Brothers and sisters
✅ [137] Rescatado: horrible harry and the drop of... -> Fear in fiction
✅ [138] Rescatado: encyclopedia brown the case de... -> Mystery and detective stories
✅ [139] Rescatado: the baby unicorn... -> Juvenile fiction
✅ [140] Rescatado: ghost beneath our feet... -> Ghosts
✅ [141] Rescatado: kate's camp-out (sleepover fri... -> Children: Grades 4-6
✅ [142] Rescatado: the secret hide-out... -> Children's fiction
✅ [143] Rescatado: no more sleepovers, patti? (sl... -> Juvenile fiction
✅ [144] Rescatado: the friendship pact (grades 4-... -> Children: Grades 4-6
✅ [145] Rescatado: marshmallow muscles, banana br... -> Cookery
✅ [146] Rescatado: clifford, we love you (cliffor... -> Dogs
.✅ [148] Rescatado: my picture book of the planets... -> Juvenile literature
✅ [149] Rescatado: the addams family... -> Haunted houses
✅ [150] Rescatado: the haunted soccer field (spor... -> Soccer stories
✅ [151] Rescatado: 101 back to school jokes... -> Jokes
✅ [152] Rescatado: the haunted trail (phantom rid... -> Horses
✅ [153] Rescatado: blood and gore, like you've ne... -> Atlases
✅ [154] Rescatado: poison in paradise! (the secre... -> Secret world of Alex Mack (Television program)
✅ [155] Rescatado: cool in school: sister, sister... -> Sisters
✅ [156] Rescatado: portion savvy : the 30-day sma... -> Food portions
✅ [157] Rescatado: mother goose house... -> Nursery rhymes
✅ [158] Rescatado: blue hat, green hat (boynton, ... -> Animals
✅ [159] Rescatado: back to school cool (fullhouse... -> Fiction
✅ [160] Rescatado: never trust a flamingo (fullho... -> Skis and skiing
✅ [161] Rescatado: ghosts of war : ghosts of war... -> Miscellanea
✅ [162] Rescatado: richard scarry's just right wo... -> Vocabulary
✅ [163] Rescatado: the three bears board book... -> Fairy tales
✅ [164] Rescatado: 26 fairmount avenue (newbery h... -> Intellectual life
✅ [165] Rescatado: the tale of benjamin bunny... -> Rabbits, fiction
✅ [166] Rescatado: dreams: a book of symbols... -> Miniature books
✅ [167] Rescatado: dinosaurs in god's world long ... -> Dinosaurs
✅ [168] Rescatado: what if cruella de vil was you... -> American wit and humor
✅ [169] Rescatado: dk readers: lego secret at dol... -> Juvenile fiction
✅ [170] Rescatado: tourist trap (rebecca schwartz... -> Fiction
✅ [171] Rescatado: the northwest murders... -> Fiction
✅ [172] Rescatado: earthquake (planet earth serie... -> Popular works
✅ [173] Rescatado: do you remember?: the book tha... -> Social life and customs
✅ [174] Rescatado: secret of the ghost piano (eas... -> Children's stories, American
✅ [175] Rescatado: caroline zucker and the birthd... -> Birthdays
✅ [176] Rescatado: amazing mazes: mind bending ma... -> Maze puzzles
✅ [177] Rescatado: rhubarb... -> Fiction
✅ [178] Rescatado: wb pony engine... -> Fire engines, fiction
..✅ [181] Rescatado: learn about dinosaurs (leap fr... -> Dinosaurs
✅ [182] Rescatado: valentine's day: things to mak... -> Handicraft
✅ [183] Rescatado: let's pretend (giant first-sta... -> Play
✅ [184] Rescatado: early bird on sesame street... -> Juvenile fiction
✅ [185] Rescatado: nature on the rampage... -> Natural disasters
✅ [186] Rescatado: return from tomorrow... -> Christian biography
✅ [187] Rescatado: kids' computer creations: usin... -> Juvenile literature
✅ [188] Rescatado: the muffin muncher... -> Fiction
✅ [189] Rescatado: sundancer... -> Freedom
✅ [190] Rescatado: how to become naturally thin b... -> Nutrition
✅ [191] Rescatado: rudolph the red-nosed reindeer... -> Fiction
✅ [192] Rescatado: bambi (disney)... -> Bambi (Fictitious character)
✅ [193] Rescatado: case of the dangerous cruise (... -> Fiction
✅ [194] Rescatado: on fire... -> Fire fighters
..✅ [197] Rescatado: yogi bear: yummy in my tummy :... -> Toy and movable books
✅ [198] Rescatado: face down among the winchester... -> Fiction, mystery & detective, general
✅ [199] Rescatado: alex alligator and his fearsom... -> Juvenile fiction
✅ [200] Rescatado: a parting gift... -> Teenage boys
.✅ [202] Rescatado: the right man for the job: a n... -> Church history
✅ [203] Rescatado: boy island... -> Fiction, general
✅ [204] Rescatado: sex signs : every woman's astr... -> Astrology and sex
✅ [205] Rescatado: the cat-dogs... -> American Horror tales
✅ [206] Rescatado: the party's over (point)... -> Self-perception
.✅ [208] Rescatado: fiddleback: a novel... -> Brothers and sisters
✅ [209] Rescatado: sheer blue bliss... -> Fiction, general
✅ [210] Rescatado: damascus gate (thorndike large... -> Fiction
✅ [211] Rescatado: cracker factory... -> Fiction
✅ [212] Rescatado: the golden ocean... -> Centurion (Ship)
✅ [213] Rescatado: penguin book of childhood... -> Literary collections
✅ [214] Rescatado: 1+1+1 une rã?â©volution... -> Politics and government
✅ [215] Rescatado: the narrowing stream... -> Fiction, general
✅ [216] Rescatado: a spanish lover... -> 1990s
✅ [217] Rescatado: we're counting on you, grover!... -> Fiction
✅ [218] Rescatado: fantastic optical illusions &a... -> Puzzles
.✅ [220] Rescatado: neighborhood watch... -> Fiction, mystery & detective, general
✅ [221] Rescatado: eve's men... -> Brothers
.✅ [223] Rescatado: metis: canada's forgotten peop... -> Government relations
✅ [224] Rescatado: the road home... -> Country life
✅ [225] Rescatado: something to talk about/movie ... -> Man-woman relationships
✅ [226] Rescatado: kartography... -> Immigrants
✅ [227] Rescatado: the alleys of eden: a novel... -> Americans
✅ [228] Rescatado: skeleton key... -> Mystery
.✅ [230] Rescatado: the case of the green ghost (t... -> Detective and mystery stories
.✅ [232] Rescatado: journaling from the heart... -> Diaries
.✅ [234] Rescatado: the case of the rolling bones ... -> American Detective and mystery stories
✅ [235] Rescatado: the last lion winston spencer ... -> Churchill, winston, 1874-1965
✅ [236] Rescatado: revolt of the masses... -> Civilization
✅ [237] Rescatado: all gods dangers... -> Sharecropping
✅ [238] Rescatado: floods, famines, and emperors ... -> History
✅ [239] Rescatado: great cases of the thinking ma... -> American Detective and mystery stories
✅ [240] Rescatado: seven complete perry mason nov... -> American Detective and mystery stories
✅ [241] Rescatado: a history of warfare... -> History
✅ [242] Rescatado: the lacquer screen... -> China, fiction
✅ [243] Rescatado: the new bedside, bathtub &amp;... -> Miscellanea
✅ [244] Rescatado: carl sagan: a life in the cosm... -> Astronomers
✅ [245] Rescatado: outside the law: narratives on... -> Justice, administration of
✅ [246] Rescatado: flim-flam! psychics, esp, unic... -> Controversial literature
✅ [247] Rescatado: the hard to catch mercy... -> South carolina, fiction
✅ [248] Rescatado: paarungen... -> Fiction
✅ [249] Rescatado: joined at the heart: the trans... -> Families
✅ [250] Rescatado: diary of anna green winslow: a... -> Juvenile literature
✅ [251] Rescatado: der schatten im norden... -> Detective and mystery stories
✅ [252] Rescatado: the future of success... -> Travail
✅ [253] Rescatado: the office scripts 1 (scripts)... -> Office (Television program : Great Britain)
✅ [254] Rescatado: a dedicated man: an inspector ... -> Fiction, mystery & detective, traditional
✅ [255] Rescatado: highland laddie gone... -> Fiction
✅ [256] Rescatado: pooh's 101 uses for a honey po... -> Conduct of life
✅ [257] Rescatado: anne's house of dreams... -> Country life
✅ [258] Rescatado: aromatherapy blends and remedi... -> Aromatherapy
✅ [259] Rescatado: lives of short duration (new c... -> Canadian fiction
✅ [260] Rescatado: maclaren's bride... -> Kidnapping
✅ [261] Rescatado: frances' story (sisters of the... -> Artists
✅ [262] Rescatado: sarah's story (sisters of the ... -> Education
✅ [263] Rescatado: beloved enemy... -> Fiction, Romance, Historical
.✅ [265] Rescatado: walt disney's peter pan (illus... -> Children's story
✅ [266] Rescatado: the town mouse and the country... -> Mice
✅ [267] Rescatado: small pleasure... -> Fathers and daughters
.✅ [269] Rescatado: fourth estate... -> Newspaper publishing
✅ [270] Rescatado: pryor rendering: a novel... -> Fiction
✅ [271] Rescatado: the theatre of the absurd.... -> Drama, history and criticism, 20th century
✅ [272] Rescatado: disney's beauty and the beast ... -> Juvenile literature
✅ [273] Rescatado: once upon a crime... -> American Historical fiction
✅ [274] Rescatado: b &amp; e... -> Detective and mystery stories
✅ [275] Rescatado: sweet poison (harlequin romanc... -> Contemporary romance
✅ [276] Rescatado: where there's will (harlequin ... -> Fiction, Romance, Contemporary
✅ [277] Rescatado: getting over harry (simply the... -> Fiction, romance, general
✅ [278] Rescatado: cowboy and the cossack (code n... -> Fiction, romance, general
✅ [279] Rescatado: old passion (harlequin present... -> Fiction, romance, general
.✅ [281] Rescatado: a ghostly affair (harlequin am... -> Fiction, general
✅ [282] Rescatado: indiscreet (harlequin intrigue... -> Fiction, mystery & detective, general
✅ [283] Rescatado: wherever love leads (harlequin... -> Courtroom artists
✅ [284] Rescatado: shaded leaves of destiny (silh... -> Fiction, romance, general
✅ [285] Rescatado: doctor's homecoming (harlequin... -> Fiction, Romance, Historical
✅ [286] Rescatado: forgotten honeymoon (fortune's... -> Fiction, general
✅ [287] Rescatado: though i know she lies... -> Antony Maitland (Fictitious character)
..✅ [290] Rescatado: honor bound groom  (fortune's ... -> Fiction, romance, general
✅ [291] Rescatado: the bodyguard's story : diana,... -> Death and burial
✅ [292] Rescatado: the promise... -> Mines and mineral resources
✅ [293] Rescatado: duty and dishonor... -> Fiction, general
✅ [294] Rescatado: the caller... -> Fiction in English
✅ [295] Rescatado: the burning bed... -> Non-Classifiable
✅ [296] Rescatado: the shadow warriors: a novel o... -> Tennessee, fiction
✅ [297] Rescatado: encyclopedia brown carries on ... -> Detective and mystery stories
✅ [298] Rescatado: we hate everything but boys : ... -> We Hate Everything But Boys
✅ [299] Rescatado: blockbuster... -> Extortion
✅ [300] Rescatado: the million dollar shot... -> Basketball
✅ [301] Rescatado: renegade bride (heartfire roma... -> Overland journeys to the Pacific
.✅ [303] Rescatado: the duke and miss denny (zebra... -> Social life and customs
.✅ [305] Rescatado: the cape cod caper... -> Fiction
✅ [306] Rescatado: acts of kindness... -> Kindness
✅ [307] Rescatado: minor adjustments... -> Insurance adjusters
✅ [308] Rescatado: in fremden kleidern. geschicht... -> American Novelists
✅ [309] Rescatado: the hunter... -> Fiction
✅ [310] Rescatado: madame de sevigne... -> Authors, French
✅ [311] Rescatado: christopher isherwood diaries:... -> 20th century
✅ [312] Rescatado: het vuur brandde voort: levens... -> Authors, Dutch
.✅ [314] Rescatado: arthur and the cootie catcher... -> Cootie catchers
✅ [315] Rescatado: entertainment weekly seinfeld ... -> Seinfeld
✅ [316] Rescatado: dear fairies... -> Fairy tales
✅ [317] Rescatado: who do you love? : your comple... -> Children's fiction
.✅ [319] Rescatado: introduction to physical anthr... -> Physical anthropology
✅ [320] Rescatado: the moviegoer... -> Fiction
✅ [321] Rescatado: portnoy's complaint... -> Coming of age
✅ [322] Rescatado: the merchants' war... -> Science fiction
✅ [323] Rescatado: crystal woman: the sisters of ... -> Religion
✅ [324] Rescatado: the good policeman... -> Fiction
✅ [325] Rescatado: marika... -> Fiction
✅ [326] Rescatado: concerning the inner life... -> Christian life
.✅ [328] Rescatado: she's a momma, not a movie sta... -> Comic books, strips
✅ [329] Rescatado: aria: the soulmarket... -> Comics & graphic novels, general
.....✅ [335] Rescatado: she: understanding feminine ps... -> Psychology
✅ [336] Rescatado: improbable wife (silhouette ro... -> Fiction, general
✅ [337] Rescatado: club cupid (harlequin temptati... -> Romance
.✅ [339] Rescatado: texas moon (man of the month/t... -> Fiction, romance, general
.✅ [341] Rescatado: the sixties: years of hope day... -> History

In [3]:
# TITLE: Simulation - Category-Inclusive Mapping
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://root:18121996@localhost/bookproject_db')

# 1. Diccionario actualizado: La clave se incluye como primer término de búsqueda
clusters = {
    'Science fiction': ['science fiction', 'space', 'aliens', 'robots', 'future'],
    'Fiction': ['fiction', 'detective', 'mystery', 'thriller', 'horror', 'suspense', 'crime'],
    'Novels': ['novels', 'romance', 'love stories', 'contemporary', 'drama', 'saga'],
    'Literature': ['literature', 'classic', 'poetry', 'anthology', 'literary', 'essays'],
    'Young': ['young', 'juvenile', 'children', 'teen', 'young adult', 'bedtime', 'school'],
    'Biography': ['biography', 'autobiography', 'memoir', 'journal'],
    'History': ['history', 'historical', 'archaeology', 'warfare'],
    'Religion': ['religion', 'christianity', 'bible', 'theology', 'spirituality', 'christian'],
    'Science & Tech': ['science & tech', 'science', 'technology', 'physics', 'math', 'computers', 'engineering', 'computer'],
    'Political science': ['political science', 'politics', 'government', 'international relations'],
    'Social sciences': ['social sciences', 'sociology', 'anthropology', 'economics'],
    'Business': ['business', 'management', 'finance', 'marketing'],
    'Lifestyle': ['lifestyle', 'self-help', 'cookbook', 'recipes', 'health', 'diet', 'gardening', 'marriage', 'family'],
    'Travel': ['travel', 'tourism', 'geography', 'exploration'],
    'Psych': ['psych', 'psychology', 'psychiatry', 'mental health'],
    'Art': ['art', 'painting', 'sculpture'],
    'Architecture': ['architecture', 'design'],
    'Theater': ['theater', 'plays'],
    'Law': ['law', 'legal', 'justice'],
    'Education': ['education', 'teaching', 'textbook'],
    'Music': ['music', 'musical'],
    'Pets': ['pets', 'dogs', 'cats', 'animals', 'animal'],
    'Languages': ['languages', 'language', 'linguistics', 'grammar', 'spanish', 'english'],
    'Photography': ['photography', 'photo'],
    'No fiction': ['no fiction', 'non-fiction', 'documentary']
}

def categorizador_estricto(texto_sucio):
    if not texto_sucio or texto_sucio == 'Long Tail':
        return texto_sucio
    
    t = str(texto_sucio).lower()
    
    # Buscamos coincidencia. El orden del diccionario determina la prioridad.
    for oficial, palabras in clusters.items():
        if any(p in t for p in palabras):
            return oficial
            
    return 'Other'

# 2. Carga de datos para simulación
print("🔍 Iniciando simulación con nombres de categoría incluidos...")
df = pd.read_sql("SELECT isbn, titulo, categoria FROM dim_libros WHERE categoria != 'Long Tail'", engine)

# 3. Aplicar lógica
df['categoria_propuesta'] = df['categoria'].apply(categorizador_estricto)

# 4. Reporte de validación
print("\n--- RESUMEN DE CATEGORIZACIÓN ---")
print(df['categoria_propuesta'].value_counts())

print("\n--- MUESTRA DE RESULTADOS ---")

🔍 Iniciando simulación con nombres de categoría incluidos...

--- RESUMEN DE CATEGORIZACIÓN ---
categoria_propuesta
Fiction              88118
Science & Tech       31055
History              23351
Young                21370
Novels               20623
Lifestyle            20423
Religion             19949
Education            16150
Literature           14317
Biography            12856
Other                11288
Business              8771
Psych                 7964
Travel                6990
Art                   6518
Science fiction       5412
Music                 3757
Pets                  2626
Law                   2432
Languages             1982
Theater               1851
Architecture          1641
Photography           1168
Political science       15
Social sciences          5
Name: count, dtype: int64

--- MUESTRA DE RESULTADOS ---

In [6]:
# TITLE: High-Impact Category Rescue (Title + Category)
import pandas as pd
from sqlalchemy import create_engine, text

engine = create_engine('mysql+pymysql://root:18121996@localhost/bookproject_db')

# Diccionario optimizado para capturar los títulos que mencionas
clusters_v3 = {
    'Science fiction': ['science fiction', 'space', 'aliens', 'robots', 'future', 'zodiac'],
    'Fiction': ['fiction', 'detective', 'mystery', 'thriller', 'horror', 'suspense', 'crime', 'adventure', 'thriller', 'the loop', 'secret history'],
    'Novels': ['romance', 'love stories', 'contemporary', 'drama', 'saga', 'novel', 'possession', 'bet me'],
    'Literature': ['literature', 'classic', 'poetry', 'anthology', 'literary', 'essays', 'dorian gray', 'silas marner', 'unbearable lightness'],
    'Young': ['juvenile', 'children', 'teen', 'young adult', 'bedtime', 'school', 'capture the castle'],
    'Biography': ['biography', 'autobiography', 'memoir', 'journal', 'personal narratives'],
    'History': ['history', 'historical', 'archaeology', 'warfare', 'commemorative'],
    'Religion': ['religion', 'christianity', 'bible', 'theology', 'spirituality', 'celestine prophecy', 'zen'],
    'Science & Tech': ['science', 'technology', 'physics', 'math', 'computers', 'engineering'],
    'Business': ['business', 'management', 'finance', 'marketing', 'values'],
    'Lifestyle': ['self-help', 'cookbook', 'recipes', 'health', 'diet', 'gardening', 'blessings', 'deliberate intent'],
    'Art': ['art', 'painting', 'sculpture', 'humor', 'comic'],
    'Travel': ['travel', 'tourism', 'geography', 'exploration', 'tesseract'],
    'Music': ['music', 'musical', 'audio', 'sound library', 'naxos', 'brilliance audio'],
    'Pets': ['pets', 'dogs', 'cats', 'animals', 'animal', 'horses']
}

def categorizador_avanzado(row):
    # Combinamos categoría y título para la búsqueda
    texto_busqueda = f"{row['categoria']} {row['titulo']}".lower()
    
    if 'Long Tail' in row['categoria']:
        return 'Long Tail'

    for oficial, palabras in clusters_v3.items():
        if any(p in texto_busqueda for p in palabras):
            return oficial
            
    return 'Other'

# 1. Cargar datos incluyendo título para el análisis
query = "SELECT isbn, titulo, categoria FROM dim_libros WHERE categoria != 'Long Tail'"
df = pd.read_sql(query, engine)

# 2. Aplicar la nueva lógica
df['categoria_nueva'] = df.apply(categorizador_avanzado, axis=1)

# 3. Verificación de los títulos importantes que mencionaste
títulos_clave = ['dorian gray', 'bet me', 'unbearable lightness', 'zen and the art', 'atonement']
revision = df[df['titulo'].str.lower().str.contains('|'.join(títulos_clave))]

print("--- COMPROBACIÓN DE TÍTULOS CRÍTICOS ---")
print(revision[['titulo', 'categoria_nueva']])

print("\n--- NUEVO RESUMEN ---")
print(df['categoria_nueva'].value_counts())

--- COMPROBACIÓN DE TÍTULOS CRÍTICOS ---
                                                   titulo categoria_nueva
2792                        unbearable lightness of being      Literature
3258    throwing the elephant: zen and the art of mana...        Religion
4345    day of atonement: a peter decker/rina lazarus ...         Fiction
4594    the unbearable lightness of being : twentieth ...         Fiction
5232                        unbearable lightness of being      Literature
...                                                   ...             ...
321233                                 definite atonement        Religion
321404  the satisfaction of christ studies in the aton...        Religion
322905                  the war of atonement october 1973         History
330392          zen and the art of motorcycle maintenance        Religion
330563  god was in christ an essay on incarnation and ...        Religion

[164 rows x 2 columns]

--- NUEVO RESUMEN ---
categoria_nueva
Fiction            92008
Other              66965
Science & Tech     28966
Novels             24271
History            23902
Religion           19099
Literature         17682
Biography          13443
Art                 9328
Business            8582
Science fiction     7296
Travel              6208
Young               3691
Music               3459
Lifestyle           2928
Pets                2804
Name: count, dtype: int64

In [7]:
# TITLE: Bulk Update - Consolidating Category & Title Heuristics
import pandas as pd
from sqlalchemy import create_engine, text
from tqdm import tqdm

engine = create_engine('mysql+pymysql://root:18121996@localhost/bookproject_db')

# 1. Tu Diccionario Maestro de 25 Categorías
clusters_final = {
    'Science fiction': ['science fiction', 'space', 'aliens', 'robots', 'future', 'zodiac', 'dystopian'],
    'Fiction': ['fiction', 'detective', 'mystery', 'thriller', 'horror', 'suspense', 'crime', 'adventure', 'fantasy'],
    'Novels': ['romance', 'love stories', 'contemporary', 'drama', 'saga', 'novel', 'possession'],
    'Literature': ['literature', 'classic', 'poetry', 'anthology', 'literary', 'essays', 'classics', 'dorian gray', 'silas marner'],
    'Young': ['young', 'juvenile', 'children', 'teen', 'young adult', 'bedtime', 'school'],
    'Biography': ['biography', 'autobiography', 'memoir', 'journal', 'personal narratives'],
    'History': ['history', 'historical', 'archaeology', 'warfare', 'commemorative'],
    'Religion': ['religion', 'christianity', 'bible', 'theology', 'spirituality', 'christian', 'god', 'zen'],
    'Science & Tech': ['science', 'technology', 'physics', 'math', 'computers', 'engineering', 'nature'],
    'Political science': ['political science', 'politics', 'government', 'international relations', 'social conditions'],
    'Social sciences': ['social sciences', 'sociology', 'anthropology', 'economics', 'social life'],
    'Business': ['business', 'management', 'finance', 'marketing'],
    'Lifestyle': ['lifestyle', 'self-help', 'cookbook', 'recipes', 'health', 'diet', 'gardening', 'marriage', 'family'],
    'Travel': ['travel', 'tourism', 'geography', 'exploration'],
    'Psych': ['psych', 'psychology', 'psychiatry', 'mental health', 'self-perception'],
    'Art': ['art', 'painting', 'sculpture', 'humor', 'comic'],
    'Architecture': ['architecture', 'design'],
    'Theater': ['theater', 'plays'],
    'Law': ['law', 'legal', 'justice'],
    'Education': ['education', 'teaching', 'textbook'],
    'Music': ['music', 'musical', 'audio', 'sound library'],
    'Pets': ['pets', 'dogs', 'cats', 'animals', 'animal', 'horses'],
    'Languages': ['languages', 'language', 'linguistics', 'grammar'],
    'Photography': ['photography', 'photo'],
    'No fiction': ['no fiction', 'non-fiction', 'documentary']
}

def categorizador_hibrido(row):
    # Buscamos en la categoría original y en el título simultáneamente
    texto_combinado = f"{row['categoria']} {row['titulo']}".lower()
    
    if 'Long Tail' in row['categoria']:
        return 'Long Tail'

    for oficial, palabras in clusters_final.items():
        if any(p in texto_combinado for p in palabras):
            return oficial
            
    return 'Other'

# 2. Carga de datos
print("📥 Cargando datos desde MySQL...")
df = pd.read_sql("SELECT isbn, titulo, categoria FROM dim_libros WHERE categoria != 'Long Tail'", engine)

# 3. Procesar cambios en memoria
print("🧠 Calculando nuevas categorías basadas en lógica híbrida...")
df['nueva_cat'] = df.apply(categorizador_hibrido, axis=1)

# 4. Filtrar solo los que realmente cambian
df_updates = df[df['categoria'] != df['nueva_cat']]

# 5. Ejecución en Base de Datos
if not df_updates.empty:
    print(f"🔄 Actualizando {len(df_updates)} registros en MySQL...")
    with engine.begin() as conn:
        for _, row in tqdm(df_updates.iterrows(), total=len(df_updates)):
            stmt = text("UPDATE dim_libros SET categoria = :nueva WHERE isbn = :isbn")
            conn.execute(stmt, {"nueva": row['nueva_cat'], "isbn": row['isbn']})
    print("\n✅ Base de datos sincronizada con la lógica actual.")
else:
    print("✨ Todo está ya al día. No se requieren cambios.")

📥 Cargando datos desde MySQL...
🧠 Calculando nuevas categorías basadas en lógica híbrida...
🔄 Actualizando 48953 registros en MySQL...

100%|██████████| 48953/48953 [00:16<00:00, 3024.78it/s]

✅ Base de datos sincronizada con la lógica actual.

In [9]:
# TITLE: Smart API Recovery - Finishing the 'Other' Block
import pandas as pd
import requests
from sqlalchemy import create_engine, text
import time
from tqdm import tqdm

engine = create_engine('mysql+pymysql://root:18121996@localhost/bookproject_db')

# 1. Diccionario Maestro de 25 Categorías (Consolidado)
clusters_v3 = {
    'Science fiction': ['science fiction', 'space', 'aliens', 'robots', 'future', 'zodiac', 'dystopian'],
    'Fiction': ['fiction', 'detective', 'mystery', 'thriller', 'horror', 'suspense', 'crime', 'adventure', 'fantasy'],
    'Novels': ['romance', 'love stories', 'contemporary', 'drama', 'saga', 'novel', 'possession'],
    'Literature': ['literature', 'classic', 'poetry', 'anthology', 'literary', 'essays', 'classics'],
    'Young': ['young', 'juvenile', 'children', 'teen', 'young adult', 'bedtime', 'school'],
    'Biography': ['biography', 'autobiography', 'memoir', 'journal', 'personal narratives'],
    'History': ['history', 'historical', 'archaeology', 'warfare'],
    'Religion': ['religion', 'christianity', 'bible', 'theology', 'spirituality', 'christian', 'god'],
    'Science & Tech': ['science', 'technology', 'physics', 'math', 'computers', 'engineering', 'nature'],
    'Political science': ['political science', 'politics', 'government', 'international relations', 'social conditions'],
    'Social sciences': ['social sciences', 'sociology', 'anthropology', 'economics', 'social life'],
    'Business': ['business', 'management', 'finance', 'marketing'],
    'Lifestyle': ['lifestyle', 'self-help', 'cookbook', 'recipes', 'health', 'diet', 'gardening'],
    'Travel': ['travel', 'tourism', 'geography', 'exploration'],
    'Psych': ['psych', 'psychology', 'psychiatry', 'mental health'],
    'Art': ['art', 'painting', 'sculpture', 'humor', 'comic'],
    'Architecture': ['architecture', 'design'],
    'Theater': ['theater', 'plays'],
    'Law': ['law', 'legal', 'justice'],
    'Education': ['education', 'teaching', 'textbook'],
    'Music': ['music', 'musical', 'audio'],
    'Pets': ['pets', 'dogs', 'cats', 'animals', 'animal', 'horses'],
    'Languages': ['languages', 'language', 'linguistics', 'grammar'],
    'Photography': ['photography', 'photo'],
    'No fiction': ['no fiction', 'non-fiction', 'documentary']
}

def categorizador_final(api_text, title):
    full_text = f"{api_text} {title}".lower()
    for oficial, palabras in clusters_v3.items():
        if any(p in full_text for p in palabras):
            return oficial
    return 'Other'

# 2. Cargar los 8,755 'Other'
print("📦 Extrayendo los últimos 'Other' de la base de datos...")
df_others = pd.read_sql("SELECT isbn, titulo FROM dim_libros WHERE categoria = 'Other'", engine)

# 3. Ejecución del rescate por API
print(f"🚀 Iniciando consulta API para {len(df_others)} registros...")

count_rescatados = 0

for index, row in tqdm(df_others.iterrows(), total=len(df_others)):
    isbn = row['isbn']
    titulo = row['titulo']
    
    try:
        # Llamada a la API de Google Books
        # Agregamos timeout para no quedarnos colgados
        response = requests.get(f"https://www.googleapis.com/books/v1/volumes?q=isbn:{isbn}", timeout=5)
        
        if response.status_code == 200:
            data = response.json()
            if "items" in data:
                # Obtenemos las categorías de Google (si existen)
                volume_info = data["items"][0].get("volumeInfo", {})
                google_cats = " ".join(volume_info.get("categories", []))
                
                # Clasificamos usando el nuevo contexto de Google + el título
                nueva_cat = categorizador_final(google_cats, titulo)
                
                # Si logramos sacarlo de 'Other', actualizamos la DB inmediatamente
                if nueva_cat != 'Other':
                    with engine.begin() as conn:
                        stmt = text("UPDATE dim_libros SET categoria = :nueva WHERE isbn = :isbn")
                        conn.execute(stmt, {"nueva": nueva_cat, "isbn": isbn})
                    count_rescatados += 1
        
        # Pausa para respetar los límites de Google
        time.sleep(0.3)
        
    except Exception as e:
        # Si falla una petición, seguimos con la siguiente
        continue

print(f"\n✅ Proceso completado. Se han logrado clasificar {count_rescatados} libros nuevos.")

📦 Extrayendo los últimos 'Other' de la base de datos...
🚀 Iniciando consulta API para 8755 registros...

100%|██████████| 8755/8755 [1:48:13<00:00,  1.35it/s]

✅ Proceso completado. Se han logrado clasificar 5053 libros nuevos.

In [10]:
# TITLE: Final Report - Categorization Success Metrics
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://root:18121996@localhost/bookproject_db')

# 1. Obtener la distribución final
query = "SELECT categoria, COUNT(*) as total FROM dim_libros GROUP BY categoria ORDER BY total DESC"
df_final = pd.read_sql(query, engine)

print("--- REPORTE FINAL DE CATEGORÍAS ---")
print(df_final.to_string(index=False))

# 2. Calcular porcentaje de limpieza (excluyendo Long Tail si aplica)
total_libros = df_final['total'].sum()
total_others = df_final[df_final['categoria'] == 'Other']['total'].sum()
clean_rate = (1 - (total_others / total_libros)) * 100

print(f"\n📊 Tasa de limpieza final: {clean_rate:.2f}%")
print(f"📉 Libros restantes en 'Other': {total_others}")

--- REPORTE FINAL DE CATEGORÍAS ---
        categoria  total
        Long Tail 129060
          Fiction  95733
   Science & Tech  29052
           Novels  24329
          History  23868
            Young  22589
        Lifestyle  19821
         Religion  19590
       Literature  17751
        Biography  13485
        Education  11430
         Business   8215
  Science fiction   7311
              Art   7213
            Psych   6635
           Travel   6246
            Other   3702
            Music   3130
             Pets   2276
              Law   2047
        Languages   1758
          Theater   1472
     Architecture   1393
      Photography    975
  Social sciences    378
Political science    233

📊 Tasa de limpieza final: 99.19%
📉 Libros restantes en 'Other': 3702

In [11]:
# TITLE: Long Tail Rescue - Priority based on Ratings
import pandas as pd
import requests
from sqlalchemy import create_engine, text
import time
from tqdm import tqdm

engine = create_engine('mysql+pymysql://root:18121996@localhost/bookproject_db')

# 1. Tu Diccionario de Categorías (Reutilizamos el v3)
clusters_v3 = {
    'Science fiction': ['science fiction', 'space', 'aliens', 'robots', 'future', 'zodiac', 'dystopian'],
    'Fiction': ['fiction', 'detective', 'mystery', 'thriller', 'horror', 'suspense', 'crime', 'adventure', 'fantasy'],
    'Novels': ['romance', 'love stories', 'contemporary', 'drama', 'saga', 'novel', 'possession'],
    'Literature': ['literature', 'classic', 'poetry', 'anthology', 'literary', 'essays', 'classics'],
    'Young': ['young', 'juvenile', 'children', 'teen', 'young adult', 'bedtime', 'school'],
    'Biography': ['biography', 'autobiography', 'memoir', 'journal', 'personal narratives'],
    'History': ['history', 'historical', 'archaeology', 'warfare'],
    'Religion': ['religion', 'christianity', 'bible', 'theology', 'spirituality', 'christian', 'god'],
    'Science & Tech': ['science', 'technology', 'physics', 'math', 'computers', 'engineering', 'nature'],
    'Political science': ['political science', 'politics', 'government', 'international relations'],
    'Social sciences': ['social sciences', 'sociology', 'anthropology', 'economics'],
    'Business': ['business', 'management', 'finance', 'marketing'],
    'Lifestyle': ['lifestyle', 'self-help', 'cookbook', 'recipes', 'health', 'diet', 'gardening'],
    'Travel': ['travel', 'tourism', 'geography', 'exploration'],
    'Psych': ['psych', 'psychology', 'psychiatry', 'mental health'],
    'Art': ['art', 'painting', 'sculpture', 'humor', 'comic'],
    'Architecture': ['architecture', 'design'],
    'Theater': ['theater', 'plays'],
    'Law': ['law', 'legal', 'justice'],
    'Education': ['education', 'teaching', 'textbook'],
    'Music': ['music', 'musical', 'audio'],
    'Pets': ['pets', 'dogs', 'cats', 'animals', 'animal', 'horses'],
    'Languages': ['languages', 'language', 'linguistics', 'grammar'],
    'Photography': ['photography', 'photo'],
    'No fiction': ['no fiction', 'non-fiction', 'documentary']
}

def categorizador_final(api_text, title):
    full_text = f"{api_text} {title}".lower()
    for oficial, palabras in clusters_v3.items():
        if any(p in full_text for p in palabras):
            return oficial
    return None # Si no encuentra nada, devolvemos None para no sobreescribir

# 2. Obtener los Long Tail más populares
print("🔍 Buscando los libros más valorados en Long Tail...")
query = """
    SELECT l.isbn, l.titulo, COUNT(r.puntuacion) as num_ratings
    FROM dim_libros l
    JOIN fact_ratings r ON l.isbn = r.isbn
    WHERE l.categoria = 'Long Tail'
    GROUP BY l.isbn, l.titulo
    HAVING num_ratings > 0
    ORDER BY num_ratings DESC
    LIMIT 1000
"""
df_top_lt = pd.read_sql(query, engine)

# 3. Rescate por API
print(f"🚀 Intentando rescatar {len(df_top_lt)} libros populares...")

rescatados = 0
for index, row in tqdm(df_top_lt.iterrows(), total=len(df_top_lt)):
    isbn, titulo = row['isbn'], row['titulo']
    
    try:
        response = requests.get(f"https://www.googleapis.com/books/v1/volumes?q=isbn:{isbn}", timeout=5)
        if response.status_code == 200:
            data = response.json()
            if "items" in data:
                g_cats = " ".join(data["items"][0].get("volumeInfo", {}).get("categories", []))
                nueva_cat = categorizador_final(g_cats, titulo)
                
                if nueva_cat:
                    with engine.begin() as conn:
                        stmt = text("UPDATE dim_libros SET categoria = :nueva WHERE isbn = :isbn")
                        conn.execute(stmt, {"nueva": nueva_cat, "isbn": isbn})
                    rescatados += 1
        time.sleep(0.3)
    except:
        continue

print(f"\n✅ ¡Misión cumplida! Se han rescatado {rescatados} libros del Long Tail.")

🔍 Buscando los libros más valorados en Long Tail...
🚀 Intentando rescatar 1000 libros populares...

100%|██████████| 1000/1000 [12:33<00:00,  1.33it/s]

✅ ¡Misión cumplida! Se han rescatado 744 libros del Long Tail.

In [12]:
# TITLE: Long Tail Rescue - Final 1000 Batch (Offset 1000)
import pandas as pd
import requests
from sqlalchemy import create_engine, text
import time
from tqdm import tqdm

engine = create_engine('mysql+pymysql://root:18121996@localhost/bookproject_db')

# 1. Diccionario Maestro (v3)
clusters_v3 = {
    'Science fiction': ['science fiction', 'space', 'aliens', 'robots', 'future', 'zodiac', 'dystopian'],
    'Fiction': ['fiction', 'detective', 'mystery', 'thriller', 'horror', 'suspense', 'crime', 'adventure', 'fantasy'],
    'Novels': ['romance', 'love stories', 'contemporary', 'drama', 'saga', 'novel', 'possession'],
    'Literature': ['literature', 'classic', 'poetry', 'anthology', 'literary', 'essays', 'classics'],
    'Young': ['young', 'juvenile', 'children', 'teen', 'young adult', 'bedtime', 'school'],
    'Biography': ['biography', 'autobiography', 'memoir', 'journal', 'personal narratives'],
    'History': ['history', 'historical', 'archaeology', 'warfare'],
    'Religion': ['religion', 'christianity', 'bible', 'theology', 'spirituality', 'christian', 'god'],
    'Science & Tech': ['science', 'technology', 'physics', 'math', 'computers', 'engineering', 'nature'],
    'Political science': ['political science', 'politics', 'government', 'international relations'],
    'Social sciences': ['social sciences', 'sociology', 'anthropology', 'economics'],
    'Business': ['business', 'management', 'finance', 'marketing'],
    'Lifestyle': ['lifestyle', 'self-help', 'cookbook', 'recipes', 'health', 'diet', 'gardening'],
    'Travel': ['travel', 'tourism', 'geography', 'exploration'],
    'Psych': ['psych', 'psychology', 'psychiatry', 'mental health'],
    'Art': ['art', 'painting', 'sculpture', 'humor', 'comic'],
    'Architecture': ['architecture', 'design'],
    'Theater': ['theater', 'plays'],
    'Law': ['law', 'legal', 'justice'],
    'Education': ['education', 'teaching', 'textbook'],
    'Music': ['music', 'musical', 'audio'],
    'Pets': ['pets', 'dogs', 'cats', 'animals', 'animal', 'horses'],
    'Languages': ['languages', 'language', 'linguistics', 'grammar'],
    'Photography': ['photography', 'photo'],
    'No fiction': ['no fiction', 'non-fiction', 'documentary']
}

def categorizador_final(api_text, title):
    full_text = f"{api_text} {title}".lower()
    for oficial, palabras in clusters_v3.items():
        if any(p in full_text for p in palabras):
            return oficial
    return None

# 2. Obtener el siguiente lote (OFFSET 1000)
print("🔍 Buscando el segundo nivel de libros populares en Long Tail...")
query = """
    SELECT l.isbn, l.titulo, COUNT(r.puntuacion) as num_ratings
    FROM dim_libros l
    JOIN fact_ratings r ON l.isbn = r.isbn
    WHERE l.categoria = 'Long Tail'
    GROUP BY l.isbn, l.titulo
    ORDER BY num_ratings DESC
    LIMIT 1000 OFFSET 1000
"""
df_top_lt = pd.read_sql(query, engine)

# 3. Rescate por API
print(f"🚀 Iniciando rescate del lote final ({len(df_top_lt)} registros)...")

rescatados = 0
for index, row in tqdm(df_top_lt.iterrows(), total=len(df_top_lt)):
    isbn, titulo = row['isbn'], row['titulo']
    
    try:
        response = requests.get(f"https://www.googleapis.com/books/v1/volumes?q=isbn:{isbn}", timeout=5)
        if response.status_code == 200:
            data = response.json()
            if "items" in data:
                g_cats = " ".join(data["items"][0].get("volumeInfo", {}).get("categories", []))
                nueva_cat = categorizador_final(g_cats, titulo)
                
                if nueva_cat:
                    with engine.begin() as conn:
                        stmt = text("UPDATE dim_libros SET categoria = :nueva WHERE isbn = :isbn")
                        conn.execute(stmt, {"nueva": nueva_cat, "isbn": isbn})
                    rescatados += 1
        time.sleep(0.3)
    except:
        continue

print(f"\n✅ Proceso finalizado. Se han rescatado {rescatados} libros adicionales.")

🔍 Buscando el segundo nivel de libros populares en Long Tail...
🚀 Iniciando rescate del lote final (1000 registros)...

100%|██████████| 1000/1000 [12:36<00:00,  1.32it/s]

✅ Proceso finalizado. Se han rescatado 751 libros adicionales.

In [2]:
# TITLE: Final Distribution Check - Clean Categories
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://root:18121996@localhost/bookproject_db')

# Verificación de la distribución tras la unión
print("--- DISTRIBUCIÓN FINAL DE LAS 25 CATEGORÍAS + OTHER ---")
query = """
    SELECT categoria, COUNT(*) as total 
    FROM dim_libros 
    GROUP BY categoria 
    ORDER BY total DESC
"""
df_check = pd.read_sql(query, engine)

# Mostramos el resultado
print(df_check.to_string(index=False))

# Cálculo de la salud del dataset
total = df_check['total'].sum()
others = df_check[df_check['categoria'] == 'Other']['total'].sum()
percent_clean = (1 - (others / total)) * 100
print(f"\n📊 El {percent_clean:.2f}% de tu catálogo está clasificado en tus categorías oficiales.")

--- DISTRIBUCIÓN FINAL DE LAS 25 CATEGORÍAS + OTHER ---
        categoria  total
            Other 131267
          Fiction  96656
   Science & Tech  29115
           Novels  24372
          History  23921
            Young  22631
        Lifestyle  19860
         Religion  19628
       Literature  17790
        Biography  13548
        Education  11435
         Business   8222
  Science fiction   7324
              Art   7276
            Psych   6652
           Travel   6260
            Music   3133
             Pets   2296
              Law   2051
        Languages   1767
          Theater   1475
     Architecture   1397
      Photography    976
  Social sciences    407
Political science    233

📊 El 71.44% de tu catálogo está clasificado en tus categorías oficiales.

In [4]:
# TITLE: Impact Analysis - Value of the 'Other' Category
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://root:18121996@localhost/bookproject_db')

# 1. Analizamos la distribución de ratings dentro de 'Other'
query = """
    SELECT 
        CASE 
            WHEN num_ratings = 0 THEN '0 ratings (Sin impacto)'
            WHEN num_ratings BETWEEN 1 AND 5 THEN '1-5 ratings (Muy bajo)'
            WHEN num_ratings BETWEEN 6 AND 20 THEN '6-20 ratings (Bajo)'
            ELSE 'Más de 20 ratings (Importantes)'
        END AS segmento_importancia,
        COUNT(*) as total_libros
    FROM (
        SELECT l.isbn, COUNT(r.puntuacion) as num_ratings
        FROM dim_libros l
        LEFT JOIN fact_ratings r ON l.isbn = r.isbn
        WHERE l.categoria = 'Other'
        GROUP BY l.isbn
    ) AS subconsulta
    GROUP BY segmento_importancia
    ORDER BY total_libros DESC
"""

print("📊 Analizando el peso real de los 131k libros en 'Other'...")
df_impacto = pd.read_sql(query, engine)

# 2. Mostramos resultados
print("\n--- SEGMENTACIÓN DE IMPORTANCIA EN 'OTHER' ---")
print(df_impacto.to_string(index=False))

# 3. Ver los "top" que se nos pudieron escapar (si existen)
print("\n--- TOP 10 LIBROS MÁS VOTADOS QUE SIGUEN EN 'OTHER' ---")
query_top = """
    SELECT l.titulo, COUNT(r.puntuacion) as votos
    FROM dim_libros l
    JOIN fact_ratings r ON l.isbn = r.isbn
    WHERE l.categoria = 'Other'
    GROUP BY l.isbn, l.titulo
    ORDER BY votos DESC
    LIMIT 10
"""
print(pd.read_sql(query_top, engine).to_string(index=False))

📊 Analizando el peso real de los 131k libros en 'Other'...

--- SEGMENTACIÓN DE IMPORTANCIA EN 'OTHER' ---
           segmento_importancia  total_libros
         1-5 ratings (Muy bajo)        125146
        0 ratings (Sin impacto)          5418
            6-20 ratings (Bajo)           597
Más de 20 ratings (Importantes)           106

--- TOP 10 LIBROS MÁS VOTADOS QUE SIGUEN EN 'OTHER' ---
                                          titulo  votos
          the unbearable lightness of being isis    309
                      the laughing corpse signed    222
                         blue book of gun values    198
                                             out    158
                                             out    158
                            a book of five rings    142
the eye of the world (the wheel of time, book 1)    131
              the blair witch project: a dossier    116
                                        up front    116
                               keynotessons lvrs    111